version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - n 18
  pre_build:
    commands:
      - printenv > .env
      - yarn install --frozen-lockfile
  build:
    commands:
      - echo Build started on `date`
      - yarn backend:build:artifacts
  post_build:
    commands:
      - echo Deploy started on `date`
      - yarn backend:deploy ${STAGE}
