version: '3.8'

services:
  mongo1:
    image: mongo:6.0.6
    platform: linux/arm64
    container_name: mongo1
    hostname: mongo1
    ports:
      - 27017:27017
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./data/mongo1:/data/db
    networks:
      - mongo-network
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongo2:
    image: mongo:6.0.6
    platform: linux/arm64
    container_name: mongo2
    hostname: mongo2
    ports:
      - 27018:27017
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./data/mongo2:/data/db
    networks:
      - mongo-network
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongo3:
    image: mongo:6.0.6
    platform: linux/arm64
    container_name: mongo3
    hostname: mongo3
    ports:
      - 27019:27017
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./data/mongo3:/data/db
    networks:
      - mongo-network
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongo-setup:
    image: mongo:6.0.6
    platform: linux/arm64
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-network
    entrypoint: >
      bash -c "
        sleep 10;
        echo 'Configuring replica set';
        mongosh --host mongo1:27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo1:27017\" },
              { _id: 1, host: \"mongo2:27017\" },
              { _id: 2, host: \"mongo3:27017\" }
            ]
          });
        '
      "

  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
  mongo-network:
    driver: bridge

volumes:
  redis-data:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
