# Use the official Node.js base image
FROM node:18-alpine

# Set the working directory in the image
WORKDIR /app

# Copy the package.json and yarn.lock from the API directory
COPY . .

# Install the API dependencies
RUN yarn install

# Build the API
RUN yarn api:build

# Expose port 4000
EXPOSE 4000

# Set the command to run the API
CMD ["yarn", "api:start"]
