version: '3.8'

services:
  mongo1:
    image: mongo:6.0.6
    platform: linux/arm64
    container_name: mongo1
    hostname: mongo1
    ports:
      - 27017:27017
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./data/mongo1:/data/db
    networks:
      - mongo-network
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongo2:
    image: mongo:6.0.6
    platform: linux/arm64
    container_name: mongo2
    hostname: mongo2
    ports:
      - 27018:27017
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./data/mongo2:/data/db
    networks:
      - mongo-network
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongo3:
    image: mongo:6.0.6
    platform: linux/arm64
    container_name: mongo3
    hostname: mongo3
    ports:
      - 27019:27017
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./data/mongo3:/data/db
    networks:
      - mongo-network
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongo-setup:
    image: mongo:6.0.6
    platform: linux/arm64
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-network
    entrypoint: >
      bash -c "
        sleep 10;
        echo 'Configuring replica set';
        mongosh --host mongo1:27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo1:27017\" },
              { _id: 1, host: \"mongo2:27017\" },
              { _id: 2, host: \"mongo3:27017\" }
            ]
          });
        '
      "

networks:
  mongo-network:
    driver: bridge
