version: '3.7'

services:
  mongodb:
    container_name: starter-mongodb
    image: mongo:6.0
    volumes:
      - starter-mongodb-data:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
    networks:
      - network

  redis:
    container_name: starter-redis
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - starter-redis-data:/data

networks:
  network:
    driver: bridge

volumes:
  starter-redis-data:
  starter-mongodb-data:
