export * as auth from './Auth.resources'
export * as file from './File.resources'
export * as otp from './OTP.resources'
export * as role from './Role.resources'
export * as store from './Store.resources'
export * as subscription from './Subscription.resources'
export * as user from './User.resources'
