service: api-e2e

frameworkVersion: '4'

custom:
  dotenv:
    path: ../../.env
    logging: false

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-dotenv-plugin

functions:
  service:
    handler: src/main.handler
    events:
      - schedule: rate(24 hours)
