service: lambda-cron-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

custom:
  dotenv:
    path: ../../.env
    logging: false

plugins:
  - serverless-dotenv-plugin

functions:
  cron:
    handler: dist/main.handler
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: true
