/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AcceptInvitePathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
	/**
	 * @description Unique identifier for invite
	 * @type string, uuid
	 */
	inviteId: string
}

export type AcceptInviteQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type AcceptInviteHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type AcceptInviteHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: AcceptInviteHeaderParamsAcceptLanguageEnum
}

/**
 * @description Invite accepted successfully.
 */
export type AcceptInvite204 = any

/**
 * @description Bad Request
 */
export type AcceptInvite400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Unauthorized
 */
export type AcceptInvite401 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Not Found
 */
export type AcceptInvite404 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Internal Server
 */
export type AcceptInvite500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type AcceptInviteMutationRequest = {
	/**
	 * @type string
	 */
	name: string
	/**
	 * @description A strong password.
	 * @type string
	 */
	password: string
}

export type AcceptInviteMutationResponse = AcceptInvite204

export type AcceptInviteMutation = {
	Response: AcceptInvite204
	Request: AcceptInviteMutationRequest
	PathParams: AcceptInvitePathParams
	QueryParams: AcceptInviteQueryParams
	HeaderParams: AcceptInviteHeaderParams
	Errors: AcceptInvite400 | AcceptInvite401 | AcceptInvite404 | AcceptInvite500
}
