/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ChangeSubscriptionPaymentMethodPathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
	/**
	 * @description Unique identifier for subscription
	 * @type string, uuid
	 */
	subscriptionId: string
}

export type ChangeSubscriptionPaymentMethodQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type ChangeSubscriptionPaymentMethodHeaderParamsAcceptLanguageEnum =
	| 'en'
	| 'es'
	| 'pt-BR'

export type ChangeSubscriptionPaymentMethodHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: ChangeSubscriptionPaymentMethodHeaderParamsAcceptLanguageEnum
}

export type IntervalsIntervalEnum35 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum35 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum33 = 'ACTIVE' | 'INACTIVE'

export type DocumentTypeEnum40 = 'INDIVIDUAL' | 'COMPANY'

export type ChangeSubscriptionPaymentMethod200StatusEnum =
	| 'TRIAL'
	| 'ACTIVE'
	| 'OVERDUE'
	| 'CANCELED'

export type IntervalsIntervalEnum36 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum36 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum34 = 'ACTIVE' | 'INACTIVE'

export type DocumentTypeEnum41 = 'INDIVIDUAL' | 'COMPANY'

export type ChangeSubscriptionPaymentMethod200StatusEnum2 =
	| 'TRIAL'
	| 'ACTIVE'
	| 'OVERDUE'
	| 'CANCELED'

export type IntervalsIntervalEnum37 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum37 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum35 = 'ACTIVE' | 'INACTIVE'

export type DocumentTypeEnum42 = 'INDIVIDUAL' | 'COMPANY'

export type ChangeSubscriptionPaymentMethod200StatusEnum3 =
	| 'TRIAL'
	| 'ACTIVE'
	| 'OVERDUE'
	| 'CANCELED'

/**
 * @description OK
 */
export type ChangeSubscriptionPaymentMethod200 =
	| {
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum35
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum35
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum33
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type string
			 */
			externalId: string
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type object
			 */
			card: {
				/**
				 * @description Token representing a securely stored payment card, typically returned by a payment provider.
				 * @type string
				 */
				token: string
				/**
				 * @description Masked card number for secure display.
				 * @type string
				 */
				number: string
				/**
				 * @description Name of the cardholder as printed on the card.
				 * @type string
				 */
				holderName: string
				/**
				 * @description Card expiration date in MM/YY format.
				 * @type string
				 */
				expirationDate: string
			}
			/**
			 * @type object
			 */
			payer: {
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string, email
				 */
				email: string
				/**
				 * @type object
				 */
				phone: {
					/**
					 * @description The ISO 3166-1 country code.
					 * @type string
					 */
					iso: string
					/**
					 * @description The international dialing code for the country, prefixed by the plus sign (+).
					 * @type string
					 */
					ddi: string
					/**
					 * @type string
					 */
					number: string
				}
				/**
				 * @type object
				 */
				document: {
					/**
					 * @type string
					 */
					number: string
					/**
					 * @type string
					 */
					type: DocumentTypeEnum40
				}
				/**
				 * @type object
				 */
				address: {
					/**
					 * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
					 * @type string
					 */
					state: string
					/**
					 * @description City name.
					 * @type string
					 */
					city: string
					/**
					 * @description ZIP or postal code, containing digits only.
					 * @type string
					 */
					zipCode: string
					/**
					 * @description Neighborhood or district name.
					 * @type string
					 */
					neighborhood: string
					/**
					 * @description Street name.
					 * @type string
					 */
					street: string
					/**
					 * @description Street number.
					 * @type string
					 */
					number: string
					/**
					 * @description Additional address details (optional).
					 */
					complement?: string | null
					/**
					 * @description Nearby reference point (optional).
					 */
					landmark?: string | null
				}
			}
			/**
			 * @type string, date-time
			 */
			nextBillingDate: string
			/**
			 * @type string, date-time
			 */
			deadline: string
			canceledAt?: string | null
			/**
			 * @default "TRIAL"
			 * @type string | undefined
			 */
			status?: ChangeSubscriptionPaymentMethod200StatusEnum
			/**
			 * @type string, date-time
			 */
			createdAt: string
			/**
			 * @type string, date-time
			 */
			updatedAt: string
	  }
	| {
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum36
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum36
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum34
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type string
			 */
			externalId: string
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type object
			 */
			payer: {
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string, email
				 */
				email: string
				/**
				 * @type object
				 */
				phone: {
					/**
					 * @description The ISO 3166-1 country code.
					 * @type string
					 */
					iso: string
					/**
					 * @description The international dialing code for the country, prefixed by the plus sign (+).
					 * @type string
					 */
					ddi: string
					/**
					 * @type string
					 */
					number: string
				}
				/**
				 * @type object
				 */
				document: {
					/**
					 * @type string
					 */
					number: string
					/**
					 * @type string
					 */
					type: DocumentTypeEnum41
				}
				/**
				 * @type object
				 */
				address: {
					/**
					 * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
					 * @type string
					 */
					state: string
					/**
					 * @description City name.
					 * @type string
					 */
					city: string
					/**
					 * @description ZIP or postal code, containing digits only.
					 * @type string
					 */
					zipCode: string
					/**
					 * @description Neighborhood or district name.
					 * @type string
					 */
					neighborhood: string
					/**
					 * @description Street name.
					 * @type string
					 */
					street: string
					/**
					 * @description Street number.
					 * @type string
					 */
					number: string
					/**
					 * @description Additional address details (optional).
					 */
					complement?: string | null
					/**
					 * @description Nearby reference point (optional).
					 */
					landmark?: string | null
				}
			}
			/**
			 * @type string, date-time
			 */
			nextBillingDate: string
			/**
			 * @type string, date-time
			 */
			deadline: string
			canceledAt?: string | null
			/**
			 * @default "TRIAL"
			 * @type string | undefined
			 */
			status?: ChangeSubscriptionPaymentMethod200StatusEnum2
			/**
			 * @type string, date-time
			 */
			createdAt: string
			/**
			 * @type string, date-time
			 */
			updatedAt: string
	  }
	| {
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum37
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum37
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum35
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type string
			 */
			externalId: string
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type object
			 */
			payer: {
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string, email
				 */
				email: string
				/**
				 * @type object
				 */
				phone: {
					/**
					 * @description The ISO 3166-1 country code.
					 * @type string
					 */
					iso: string
					/**
					 * @description The international dialing code for the country, prefixed by the plus sign (+).
					 * @type string
					 */
					ddi: string
					/**
					 * @type string
					 */
					number: string
				}
				/**
				 * @type object
				 */
				document: {
					/**
					 * @type string
					 */
					number: string
					/**
					 * @type string
					 */
					type: DocumentTypeEnum42
				}
				/**
				 * @type object
				 */
				address: {
					/**
					 * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
					 * @type string
					 */
					state: string
					/**
					 * @description City name.
					 * @type string
					 */
					city: string
					/**
					 * @description ZIP or postal code, containing digits only.
					 * @type string
					 */
					zipCode: string
					/**
					 * @description Neighborhood or district name.
					 * @type string
					 */
					neighborhood: string
					/**
					 * @description Street name.
					 * @type string
					 */
					street: string
					/**
					 * @description Street number.
					 * @type string
					 */
					number: string
					/**
					 * @description Additional address details (optional).
					 */
					complement?: string | null
					/**
					 * @description Nearby reference point (optional).
					 */
					landmark?: string | null
				}
			}
			/**
			 * @type string, date-time
			 */
			nextBillingDate: string
			/**
			 * @type string, date-time
			 */
			deadline: string
			canceledAt?: string | null
			/**
			 * @default "TRIAL"
			 * @type string | undefined
			 */
			status?: ChangeSubscriptionPaymentMethod200StatusEnum3
			/**
			 * @type string, date-time
			 */
			createdAt: string
			/**
			 * @type string, date-time
			 */
			updatedAt: string
	  }

/**
 * @description Bad Request
 */
export type ChangeSubscriptionPaymentMethod400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Internal Server
 */
export type ChangeSubscriptionPaymentMethod500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type ChangeSubscriptionPaymentMethodMutationRequest =
	| {
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @description Token representing a securely stored payment card, typically returned by a payment provider.
			 * @type string
			 */
			cardToken: string
	  }
	| {
			/**
			 * @type string
			 */
			paymentMethod: string
	  }
	| {
			/**
			 * @type string
			 */
			paymentMethod: string
	  }

export type ChangeSubscriptionPaymentMethodMutationResponse =
	ChangeSubscriptionPaymentMethod200

export type ChangeSubscriptionPaymentMethodMutation = {
	Response: ChangeSubscriptionPaymentMethod200
	Request: ChangeSubscriptionPaymentMethodMutationRequest
	PathParams: ChangeSubscriptionPaymentMethodPathParams
	QueryParams: ChangeSubscriptionPaymentMethodQueryParams
	HeaderParams: ChangeSubscriptionPaymentMethodHeaderParams
	Errors:
		| ChangeSubscriptionPaymentMethod400
		| ChangeSubscriptionPaymentMethod500
}
