/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateWorkspaceQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type CreateWorkspaceHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type CreateWorkspaceHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: CreateWorkspaceHeaderParamsAcceptLanguageEnum;
};

export type DocumentTypeEnum44 = "INDIVIDUAL" | "COMPANY";

export type LocaleDefaultLocaleEnum4 = "en" | "es" | "pt-BR";

export type LocaleAvailableLocalesEnum4 = "en" | "es" | "pt-BR";

export type CreateWorkspace200StatusEnum = "TRIAL" | "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type CreateWorkspace200 = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    recurrenceExternalId?: (string | null);
    /**
     * @type string
    */
    name: string;
    email?: (string | null);
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum44;
    } | null);
    address?: ({
        /**
         * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
         * @type string
        */
        state: string;
        /**
         * @description City name.
         * @type string
        */
        city: string;
        /**
         * @description ZIP or postal code, containing digits only.
         * @type string
        */
        zipCode: string;
        /**
         * @description Neighborhood or district name.
         * @type string
        */
        neighborhood: string;
        /**
         * @description Street name.
         * @type string
        */
        street: string;
        /**
         * @description Street number.
         * @type string
        */
        number: string;
        /**
         * @type object
        */
        location: {
            /**
             * @description Latitude coordinate.
             * @type string
            */
            lat: string;
            /**
             * @description Longitude coordinate.
             * @type string
            */
            lng: string;
        };
        /**
         * @description Additional address details (optional).
        */
        complement?: (string | null);
        /**
         * @description Nearby reference point (optional).
        */
        landmark?: (string | null);
    } | null);
    logo?: (string | null);
    domain?: (string | null);
    locale?: ({
        /**
         * @type string
        */
        defaultLocale: LocaleDefaultLocaleEnum4;
        /**
         * @type array | undefined
        */
        availableLocales?: LocaleAvailableLocalesEnum4[];
    } | null);
    trialEndsAt?: (string | null);
    /**
     * @default "TRIAL"
     * @type string | undefined
    */
    status?: CreateWorkspace200StatusEnum;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type CreateWorkspace400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type CreateWorkspace500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type CreateWorkspaceMutationRequest = {
    /**
     * @type string
    */
    name: string;
};

export type CreateWorkspaceMutationResponse = CreateWorkspace200;

export type CreateWorkspaceMutation = {
    Response: CreateWorkspace200;
    Request: CreateWorkspaceMutationRequest;
    QueryParams: CreateWorkspaceQueryParams;
    HeaderParams: CreateWorkspaceHeaderParams;
    Errors: CreateWorkspace400 | CreateWorkspace500;
};