/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateSubscriptionPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type CreateSubscriptionQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type CreateSubscriptionHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type CreateSubscriptionHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: CreateSubscriptionHeaderParamsAcceptLanguageEnum;
};

export type IntervalsIntervalEnum29 = "DAY" | "WEEK" | "MONTH" | "YEAR";

export type IntervalsStatusEnum29 = "ACTIVE" | "INACTIVE";

export type PlanStatusEnum27 = "ACTIVE" | "INACTIVE";

export type DocumentTypeEnum31 = "INDIVIDUAL" | "COMPANY";

export type CreateSubscription200StatusEnum = "TRIAL" | "ACTIVE" | "OVERDUE" | "CANCELED";

export type IntervalsIntervalEnum30 = "DAY" | "WEEK" | "MONTH" | "YEAR";

export type IntervalsStatusEnum30 = "ACTIVE" | "INACTIVE";

export type PlanStatusEnum28 = "ACTIVE" | "INACTIVE";

export type DocumentTypeEnum32 = "INDIVIDUAL" | "COMPANY";

export type CreateSubscription200StatusEnum2 = "TRIAL" | "ACTIVE" | "OVERDUE" | "CANCELED";

export type IntervalsIntervalEnum31 = "DAY" | "WEEK" | "MONTH" | "YEAR";

export type IntervalsStatusEnum31 = "ACTIVE" | "INACTIVE";

export type PlanStatusEnum29 = "ACTIVE" | "INACTIVE";

export type DocumentTypeEnum33 = "INDIVIDUAL" | "COMPANY";

export type CreateSubscription200StatusEnum3 = "TRIAL" | "ACTIVE" | "OVERDUE" | "CANCELED";

/**
 * @description OK
*/
export type CreateSubscription200 = ({
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    plan: {
        /**
         * @description Unique identifier for plan
         * @type string, uuid
        */
        planId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type array | undefined
        */
        features?: {
            /**
             * @description Unique identifier for planFeature
             * @type string, uuid
            */
            planFeatureId: string;
            /**
             * @type string
            */
            description: string;
            /**
             * @type string
            */
            feature: string;
            /**
             * @type object
            */
            props: {
                /**
                 * @type number
                */
                maxOrganizations: number;
            };
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type array | undefined
        */
        intervals?: {
            /**
             * @description Unique identifier for planInterval
             * @type string, uuid
            */
            planIntervalId: string;
            /**
             * @type string
            */
            externalId: string;
            /**
             * @minLength 0
             * @type number
            */
            amount: number;
            /**
             * @type string
            */
            interval: IntervalsIntervalEnum29;
            /**
             * @type number
            */
            intervalCount: number;
            /**
             * @default 7
             * @type number | undefined
            */
            trialDays?: number;
            /**
             * @default "ACTIVE"
             * @type string | undefined
            */
            status?: IntervalsStatusEnum29;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @default false
         * @type boolean | undefined
        */
        highlight?: boolean;
        /**
         * @default false
         * @type boolean | undefined
        */
        default?: boolean;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: PlanStatusEnum27;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    };
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    card: {
        /**
         * @description Token representing a securely stored payment card, typically returned by a payment provider.
         * @type string
        */
        token: string;
        /**
         * @description Masked card number for secure display.
         * @type string
        */
        number: string;
        /**
         * @description Name of the cardholder as printed on the card.
         * @type string
        */
        holderName: string;
        /**
         * @description Card expiration date in MM/YY format.
         * @type string
        */
        expirationDate: string;
    };
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum31;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
            /**
             * @description Nearby reference point (optional).
            */
            landmark?: (string | null);
        };
    };
    /**
     * @type string, date-time
    */
    nextBillingDate: string;
    /**
     * @type string, date-time
    */
    deadline: string;
    canceledAt?: (string | null);
    /**
     * @default "TRIAL"
     * @type string | undefined
    */
    status?: CreateSubscription200StatusEnum;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
} | {
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    plan: {
        /**
         * @description Unique identifier for plan
         * @type string, uuid
        */
        planId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type array | undefined
        */
        features?: {
            /**
             * @description Unique identifier for planFeature
             * @type string, uuid
            */
            planFeatureId: string;
            /**
             * @type string
            */
            description: string;
            /**
             * @type string
            */
            feature: string;
            /**
             * @type object
            */
            props: {
                /**
                 * @type number
                */
                maxOrganizations: number;
            };
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type array | undefined
        */
        intervals?: {
            /**
             * @description Unique identifier for planInterval
             * @type string, uuid
            */
            planIntervalId: string;
            /**
             * @type string
            */
            externalId: string;
            /**
             * @minLength 0
             * @type number
            */
            amount: number;
            /**
             * @type string
            */
            interval: IntervalsIntervalEnum30;
            /**
             * @type number
            */
            intervalCount: number;
            /**
             * @default 7
             * @type number | undefined
            */
            trialDays?: number;
            /**
             * @default "ACTIVE"
             * @type string | undefined
            */
            status?: IntervalsStatusEnum30;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @default false
         * @type boolean | undefined
        */
        highlight?: boolean;
        /**
         * @default false
         * @type boolean | undefined
        */
        default?: boolean;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: PlanStatusEnum28;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    };
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum32;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
            /**
             * @description Nearby reference point (optional).
            */
            landmark?: (string | null);
        };
    };
    /**
     * @type string, date-time
    */
    nextBillingDate: string;
    /**
     * @type string, date-time
    */
    deadline: string;
    canceledAt?: (string | null);
    /**
     * @default "TRIAL"
     * @type string | undefined
    */
    status?: CreateSubscription200StatusEnum2;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
} | {
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    plan: {
        /**
         * @description Unique identifier for plan
         * @type string, uuid
        */
        planId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type array | undefined
        */
        features?: {
            /**
             * @description Unique identifier for planFeature
             * @type string, uuid
            */
            planFeatureId: string;
            /**
             * @type string
            */
            description: string;
            /**
             * @type string
            */
            feature: string;
            /**
             * @type object
            */
            props: {
                /**
                 * @type number
                */
                maxOrganizations: number;
            };
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type array | undefined
        */
        intervals?: {
            /**
             * @description Unique identifier for planInterval
             * @type string, uuid
            */
            planIntervalId: string;
            /**
             * @type string
            */
            externalId: string;
            /**
             * @minLength 0
             * @type number
            */
            amount: number;
            /**
             * @type string
            */
            interval: IntervalsIntervalEnum31;
            /**
             * @type number
            */
            intervalCount: number;
            /**
             * @default 7
             * @type number | undefined
            */
            trialDays?: number;
            /**
             * @default "ACTIVE"
             * @type string | undefined
            */
            status?: IntervalsStatusEnum31;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @default false
         * @type boolean | undefined
        */
        highlight?: boolean;
        /**
         * @default false
         * @type boolean | undefined
        */
        default?: boolean;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: PlanStatusEnum29;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    };
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum33;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
            /**
             * @description Nearby reference point (optional).
            */
            landmark?: (string | null);
        };
    };
    /**
     * @type string, date-time
    */
    nextBillingDate: string;
    /**
     * @type string, date-time
    */
    deadline: string;
    canceledAt?: (string | null);
    /**
     * @default "TRIAL"
     * @type string | undefined
    */
    status?: CreateSubscription200StatusEnum3;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
});

/**
 * @description Bad Request
*/
export type CreateSubscription400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type CreateSubscription500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type DocumentTypeEnum34 = "INDIVIDUAL" | "COMPANY";

export type DocumentTypeEnum35 = "INDIVIDUAL" | "COMPANY";

export type DocumentTypeEnum36 = "INDIVIDUAL" | "COMPANY";

export type CreateSubscriptionMutationRequest = ({
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum34;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
            /**
             * @description Nearby reference point (optional).
            */
            landmark?: (string | null);
        };
    };
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @description Token representing a securely stored payment card, typically returned by a payment provider.
     * @type string
    */
    cardToken: string;
} | {
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum35;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
            /**
             * @description Nearby reference point (optional).
            */
            landmark?: (string | null);
        };
    };
    /**
     * @type string
    */
    paymentMethod: string;
} | {
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum36;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
            /**
             * @description Nearby reference point (optional).
            */
            landmark?: (string | null);
        };
    };
    /**
     * @type string
    */
    paymentMethod: string;
});

export type CreateSubscriptionMutationResponse = CreateSubscription200;

export type CreateSubscriptionMutation = {
    Response: CreateSubscription200;
    Request: CreateSubscriptionMutationRequest;
    PathParams: CreateSubscriptionPathParams;
    QueryParams: CreateSubscriptionQueryParams;
    HeaderParams: CreateSubscriptionHeaderParams;
    Errors: CreateSubscription400 | CreateSubscription500;
};