/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateOrganizationPathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
}

export type CreateOrganizationQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type CreateOrganizationHeaderParamsAcceptLanguageEnum =
	| 'en'
	| 'es'
	| 'pt-BR'

export type CreateOrganizationHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: CreateOrganizationHeaderParamsAcceptLanguageEnum
}

export type DocumentTypeEnum16 = 'INDIVIDUAL' | 'COMPANY'

export type CreateOrganization201StatusEnum = 'ACTIVE' | 'INACTIVE'

/**
 * @description Created
 */
export type CreateOrganization201 = {
	/**
	 * @description Unique identifier for organization
	 * @type string, uuid
	 */
	organizationId: string
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
	/**
	 * @type string
	 */
	name: string
	email?: string | null
	phone?: {
		/**
		 * @description The ISO 3166-1 country code.
		 * @type string
		 */
		iso: string
		/**
		 * @description The international dialing code for the country, prefixed by the plus sign (+).
		 * @type string
		 */
		ddi: string
		/**
		 * @type string
		 */
		number: string
	} | null
	document?: {
		/**
		 * @type string
		 */
		number: string
		/**
		 * @type string
		 */
		type: DocumentTypeEnum16
	} | null
	logo?: string | null
	domain?: string | null
	/**
	 * @type string
	 */
	status: CreateOrganization201StatusEnum
	deletedAt?: string | null
	/**
	 * @type string, date-time
	 */
	createdAt: string
	/**
	 * @type string, date-time
	 */
	updatedAt: string
}

/**
 * @description Bad Request
 */
export type CreateOrganization400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Internal Server
 */
export type CreateOrganization500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type CreateOrganizationMutationRequestStatusEnum = 'ACTIVE' | 'INACTIVE'

export type CreateOrganizationMutationRequest = {
	/**
	 * @type string
	 */
	name: string
	/**
	 * @type string
	 */
	status: CreateOrganizationMutationRequestStatusEnum
}

export type CreateOrganizationMutationResponse = CreateOrganization201

export type CreateOrganizationMutation = {
	Response: CreateOrganization201
	Request: CreateOrganizationMutationRequest
	PathParams: CreateOrganizationPathParams
	QueryParams: CreateOrganizationQueryParams
	HeaderParams: CreateOrganizationHeaderParams
	Errors: CreateOrganization400 | CreateOrganization500
}
