/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateSubscriptionPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type CreateSubscriptionQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type DocumentTypeEnum10 = "INDIVIDUAL" | "COMPANY";

export type CreateSubscription200StatusEnum = "TRIAL" | "ACTIVE" | "OVERDUE" | "CANCELED";

export type DocumentTypeEnum11 = "INDIVIDUAL" | "COMPANY";

export type CreateSubscription200StatusEnum2 = "TRIAL" | "ACTIVE" | "OVERDUE" | "CANCELED";

export type DocumentTypeEnum12 = "INDIVIDUAL" | "COMPANY";

export type CreateSubscription200StatusEnum3 = "TRIAL" | "ACTIVE" | "OVERDUE" | "CANCELED";

/**
 * @description OK
*/
export type CreateSubscription200 = ({
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type number
    */
    amount: number;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    card: {
        /**
         * @description Token representing a securely stored payment card, typically returned by a payment provider.
         * @type string
        */
        token: string;
        /**
         * @description Masked card number for secure display.
         * @type string
        */
        number: string;
        /**
         * @description Name of the cardholder as printed on the card.
         * @type string
        */
        holderName: string;
        /**
         * @description Card expiration date in MM/YY format.
         * @type string
        */
        expirationDate: string;
    };
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @description Represents document types for individuals or companies
             * @type string
            */
            type: DocumentTypeEnum10;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
        };
    };
    /**
     * @type string, date-time
    */
    deadline: string;
    canceledAt?: (string | null);
    /**
     * @default "TRIAL"
     * @type string | undefined
    */
    status?: CreateSubscription200StatusEnum;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
} | {
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type number
    */
    amount: number;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @description Represents document types for individuals or companies
             * @type string
            */
            type: DocumentTypeEnum11;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
        };
    };
    /**
     * @type string, date-time
    */
    deadline: string;
    canceledAt?: (string | null);
    /**
     * @default "TRIAL"
     * @type string | undefined
    */
    status?: CreateSubscription200StatusEnum2;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
} | {
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type number
    */
    amount: number;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @description Represents document types for individuals or companies
             * @type string
            */
            type: DocumentTypeEnum12;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
        };
    };
    /**
     * @type string, date-time
    */
    deadline: string;
    canceledAt?: (string | null);
    /**
     * @default "TRIAL"
     * @type string | undefined
    */
    status?: CreateSubscription200StatusEnum3;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
});

/**
 * @description Bad Request
*/
export type CreateSubscription400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type CreateSubscription500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type DocumentTypeEnum13 = "INDIVIDUAL" | "COMPANY";

export type DocumentTypeEnum14 = "INDIVIDUAL" | "COMPANY";

export type DocumentTypeEnum15 = "INDIVIDUAL" | "COMPANY";

export type CreateSubscriptionMutationRequest = ({
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @description Represents document types for individuals or companies
             * @type string
            */
            type: DocumentTypeEnum13;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
        };
    };
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @description Token representing a securely stored payment card, typically returned by a payment provider.
     * @type string
    */
    cardToken: string;
} | {
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @description Represents document types for individuals or companies
             * @type string
            */
            type: DocumentTypeEnum14;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
        };
    };
    /**
     * @type string
    */
    paymentMethod: string;
} | {
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    payer: {
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        /**
         * @type object
        */
        phone: {
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        };
        /**
         * @type object
        */
        document: {
            /**
             * @type string
            */
            number: string;
            /**
             * @description Represents document types for individuals or companies
             * @type string
            */
            type: DocumentTypeEnum15;
        };
        /**
         * @type object
        */
        address: {
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
        };
    };
    /**
     * @type string
    */
    paymentMethod: string;
});

export type CreateSubscriptionMutationResponse = CreateSubscription200;

export type CreateSubscriptionMutation = {
    Response: CreateSubscription200;
    Request: CreateSubscriptionMutationRequest;
    PathParams: CreateSubscriptionPathParams;
    QueryParams: CreateSubscriptionQueryParams;
    Errors: CreateSubscription400 | CreateSubscription500;
};