/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateOrganizationPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type CreateOrganizationQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type CreateOrganization201StatusEnum = "ACTIVE" | "INACTIVE";

/**
 * @description Created
*/
export type CreateOrganization201 = {
    /**
     * @description Unique identifier for organization
     * @type string, uuid
    */
    organizationId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: CreateOrganization201StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type CreateOrganization400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type CreateOrganization500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type CreateOrganizationMutationRequestStatusEnum = "ACTIVE" | "INACTIVE";

export type CreateOrganizationMutationRequest = {
    /**
     * @type string
    */
    name: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: CreateOrganizationMutationRequestStatusEnum;
};

export type CreateOrganizationMutationResponse = CreateOrganization201;

export type CreateOrganizationMutation = {
    Response: CreateOrganization201;
    Request: CreateOrganizationMutationRequest;
    PathParams: CreateOrganizationPathParams;
    QueryParams: CreateOrganizationQueryParams;
    Errors: CreateOrganization400 | CreateOrganization500;
};