/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateUserPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type CreateUserQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type CreateUser201StatusEnum = "ACTIVE" | "INACTIVE";

/**
 * @description Created
*/
export type CreateUser201 = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    avatar?: (string | null);
    socialGoogleId?: (string | null);
    socialFacebookId?: (string | null);
    /**
     * @minLength 8
     * @type string
    */
    password: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: CreateUser201StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type CreateUser400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type CreateUser500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type CreateUserMutationRequest = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    avatar?: (string | null);
    /**
     * @minLength 8
     * @type string
    */
    password: string;
    /**
     * @type array
    */
    organizations: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @type array
        */
        roleIds: string[];
    }[];
};

export type CreateUserMutationResponse = CreateUser201;

export type CreateUserMutation = {
    Response: CreateUser201;
    Request: CreateUserMutationRequest;
    PathParams: CreateUserPathParams;
    QueryParams: CreateUserQueryParams;
    Errors: CreateUser400 | CreateUser500;
};