/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeactivateProfileQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type DeactivateProfileHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type DeactivateProfileHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: DeactivateProfileHeaderParamsAcceptLanguageEnum;
};

/**
 * @description The account was successfully deactivated.
*/
export type DeactivateProfile204 = any;

/**
 * @description Bad Request
*/
export type DeactivateProfile400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type DeactivateProfile401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type DeactivateProfile500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type DeactivateProfileMutationResponse = DeactivateProfile204;

export type DeactivateProfileMutation = {
    Response: DeactivateProfile204;
    QueryParams: DeactivateProfileQueryParams;
    HeaderParams: DeactivateProfileHeaderParams;
    Errors: DeactivateProfile400 | DeactivateProfile401 | DeactivateProfile500;
};