/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteOrganizationPathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
	/**
	 * @description Unique identifier for organization
	 * @type string, uuid
	 */
	organizationId: string
}

export type DeleteOrganizationQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type DeleteOrganizationHeaderParamsAcceptLanguageEnum =
	| 'en'
	| 'es'
	| 'pt-BR'

export type DeleteOrganizationHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: DeleteOrganizationHeaderParamsAcceptLanguageEnum
}

/**
 * @description Organization has been successfully deleted.
 */
export type DeleteOrganization204 = any

/**
 * @description Bad Request
 */
export type DeleteOrganization400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Internal Server
 */
export type DeleteOrganization500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type DeleteOrganizationMutationResponse = DeleteOrganization204

export type DeleteOrganizationMutation = {
	Response: DeleteOrganization204
	PathParams: DeleteOrganizationPathParams
	QueryParams: DeleteOrganizationQueryParams
	HeaderParams: DeleteOrganizationHeaderParams
	Errors: DeleteOrganization400 | DeleteOrganization500
}
