/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteUserPathParams = {
	/**
	 * @description Unique identifier for user
	 * @type string, uuid
	 */
	userId: string
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
}

export type DeleteUserQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type DeleteUserHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type DeleteUserHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: DeleteUserHeaderParamsAcceptLanguageEnum
}

/**
 * @description User has been successfully deleted.
 */
export type DeleteUser204 = any

/**
 * @description Bad Request
 */
export type DeleteUser400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Internal Server
 */
export type DeleteUser500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type DeleteUserMutationResponse = DeleteUser204

export type DeleteUserMutation = {
	Response: DeleteUser204
	PathParams: DeleteUserPathParams
	QueryParams: DeleteUserQueryParams
	HeaderParams: DeleteUserHeaderParams
	Errors: DeleteUser400 | DeleteUser500
}
