/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ForgotPasswordQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type ForgotPasswordHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type ForgotPasswordHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: ForgotPasswordHeaderParamsAcceptLanguageEnum;
};

/**
 * @description OK
*/
export type ForgotPassword200 = {
    /**
     * @description JWT access token used to authenticate API requests.
     * @type string
    */
    accessToken: string;
    /**
     * @description JWT refresh token used to obtain new access tokens.
     * @type string
    */
    refreshToken: string;
    /**
     * @description Type of token returned. Usually \"Bearer\".
     * @default "Bearer"
     * @type string | undefined
    */
    tokenType?: string;
    /**
     * @description Access token expiration time in hours.
     * @type number
    */
    expiresIn: number;
};

/**
 * @description Bad Request
*/
export type ForgotPassword400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type ForgotPassword401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Forbidden
*/
export type ForgotPassword403 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Not Found
*/
export type ForgotPassword404 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Conflict
*/
export type ForgotPassword409 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type ForgotPassword500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type ForgotPasswordMutationRequest = {
    /**
     * @type string, email
    */
    email: string;
    /**
     * @description A strong password.
     * @type string
    */
    password: string;
    otpVerification: {
        /**
         * @description Unique identifier for otp
         * @type string, uuid
        */
        otpId: string;
        /**
         * @minLength 4
         * @maxLength 4
         * @type string
        */
        code: string;
    };
};

export type ForgotPasswordMutationResponse = ForgotPassword200;

export type ForgotPasswordMutation = {
    Response: ForgotPassword200;
    Request: ForgotPasswordMutationRequest;
    QueryParams: ForgotPasswordQueryParams;
    HeaderParams: ForgotPasswordHeaderParams;
    Errors: ForgotPassword400 | ForgotPassword401 | ForgotPassword403 | ForgotPassword404 | ForgotPassword409 | ForgotPassword500;
};