/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetInvoicePathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for invoice
     * @type string, uuid
    */
    invoiceId: string;
};

export type GetInvoiceQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type GetInvoiceHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type GetInvoiceHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: GetInvoiceHeaderParamsAcceptLanguageEnum;
};

export type IntervalsIntervalEnum21 = "DAY" | "WEEK" | "MONTH" | "YEAR";

export type IntervalsStatusEnum21 = "ACTIVE" | "INACTIVE";

export type PlanStatusEnum21 = "ACTIVE" | "INACTIVE";

export type GetInvoice200StatusEnum = "PENDING" | "PAID" | "OVERDUE" | "CANCELED";

export type IntervalsIntervalEnum22 = "DAY" | "WEEK" | "MONTH" | "YEAR";

export type IntervalsStatusEnum22 = "ACTIVE" | "INACTIVE";

export type PlanStatusEnum22 = "ACTIVE" | "INACTIVE";

export type GetInvoice200StatusEnum2 = "PENDING" | "PAID" | "OVERDUE" | "CANCELED";

export type IntervalsIntervalEnum23 = "DAY" | "WEEK" | "MONTH" | "YEAR";

export type IntervalsStatusEnum23 = "ACTIVE" | "INACTIVE";

export type PlanStatusEnum23 = "ACTIVE" | "INACTIVE";

export type GetInvoice200StatusEnum3 = "PENDING" | "PAID" | "OVERDUE" | "CANCELED";

/**
 * @description OK
*/
export type GetInvoice200 = ({
    /**
     * @description Unique identifier for invoice
     * @type string, uuid
    */
    invoiceId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    plan: {
        /**
         * @description Unique identifier for plan
         * @type string, uuid
        */
        planId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type array | undefined
        */
        features?: {
            /**
             * @description Unique identifier for planFeature
             * @type string, uuid
            */
            planFeatureId: string;
            /**
             * @type string
            */
            description: string;
            /**
             * @type string
            */
            feature: string;
            /**
             * @type object
            */
            props: {
                /**
                 * @type number
                */
                maxOrganizations: number;
            };
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type array | undefined
        */
        intervals?: {
            /**
             * @description Unique identifier for planInterval
             * @type string, uuid
            */
            planIntervalId: string;
            /**
             * @type string
            */
            externalId: string;
            /**
             * @minLength 0
             * @type number
            */
            amount: number;
            /**
             * @type string
            */
            interval: IntervalsIntervalEnum21;
            /**
             * @type number
            */
            intervalCount: number;
            /**
             * @default 7
             * @type number | undefined
            */
            trialDays?: number;
            /**
             * @default "ACTIVE"
             * @type string | undefined
            */
            status?: IntervalsStatusEnum21;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @default false
         * @type boolean | undefined
        */
        highlight?: boolean;
        /**
         * @default false
         * @type boolean | undefined
        */
        default?: boolean;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: PlanStatusEnum21;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    };
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type number
    */
    amount: number;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    card: {
        /**
         * @description Token representing a securely stored payment card, typically returned by a payment provider.
         * @type string
        */
        token: string;
        /**
         * @description Masked card number for secure display.
         * @type string
        */
        number: string;
        /**
         * @description Name of the cardholder as printed on the card.
         * @type string
        */
        holderName: string;
        /**
         * @description Card expiration date in MM/YY format.
         * @type string
        */
        expirationDate: string;
    };
    /**
     * @type string, date-time
    */
    dueDate: string;
    /**
     * @type string, date-time
    */
    issuedAt: string;
    paidAt?: (string | null);
    overdueAt?: (string | null);
    canceledAt?: (string | null);
    /**
     * @default "PENDING"
     * @type string | undefined
    */
    status?: GetInvoice200StatusEnum;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
} | {
    /**
     * @description Unique identifier for invoice
     * @type string, uuid
    */
    invoiceId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    plan: {
        /**
         * @description Unique identifier for plan
         * @type string, uuid
        */
        planId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type array | undefined
        */
        features?: {
            /**
             * @description Unique identifier for planFeature
             * @type string, uuid
            */
            planFeatureId: string;
            /**
             * @type string
            */
            description: string;
            /**
             * @type string
            */
            feature: string;
            /**
             * @type object
            */
            props: {
                /**
                 * @type number
                */
                maxOrganizations: number;
            };
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type array | undefined
        */
        intervals?: {
            /**
             * @description Unique identifier for planInterval
             * @type string, uuid
            */
            planIntervalId: string;
            /**
             * @type string
            */
            externalId: string;
            /**
             * @minLength 0
             * @type number
            */
            amount: number;
            /**
             * @type string
            */
            interval: IntervalsIntervalEnum22;
            /**
             * @type number
            */
            intervalCount: number;
            /**
             * @default 7
             * @type number | undefined
            */
            trialDays?: number;
            /**
             * @default "ACTIVE"
             * @type string | undefined
            */
            status?: IntervalsStatusEnum22;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @default false
         * @type boolean | undefined
        */
        highlight?: boolean;
        /**
         * @default false
         * @type boolean | undefined
        */
        default?: boolean;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: PlanStatusEnum22;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    };
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type number
    */
    amount: number;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    pix: {
        /**
         * @description URL containing the Pix QR Code payload, used to initiate a payment.
         * @type string, uri
        */
        qrCodeUrl: string;
        /**
         * @description Expiration date and time for the Pix payment in ISO format.
         * @type string, date-time
        */
        expiresAt: string;
    };
    /**
     * @type string, date-time
    */
    dueDate: string;
    /**
     * @type string, date-time
    */
    issuedAt: string;
    paidAt?: (string | null);
    overdueAt?: (string | null);
    canceledAt?: (string | null);
    /**
     * @default "PENDING"
     * @type string | undefined
    */
    status?: GetInvoice200StatusEnum2;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
} | {
    /**
     * @description Unique identifier for invoice
     * @type string, uuid
    */
    invoiceId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for subscription
     * @type string, uuid
    */
    subscriptionId: string;
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type object
    */
    plan: {
        /**
         * @description Unique identifier for plan
         * @type string, uuid
        */
        planId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type array | undefined
        */
        features?: {
            /**
             * @description Unique identifier for planFeature
             * @type string, uuid
            */
            planFeatureId: string;
            /**
             * @type string
            */
            description: string;
            /**
             * @type string
            */
            feature: string;
            /**
             * @type object
            */
            props: {
                /**
                 * @type number
                */
                maxOrganizations: number;
            };
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type array | undefined
        */
        intervals?: {
            /**
             * @description Unique identifier for planInterval
             * @type string, uuid
            */
            planIntervalId: string;
            /**
             * @type string
            */
            externalId: string;
            /**
             * @minLength 0
             * @type number
            */
            amount: number;
            /**
             * @type string
            */
            interval: IntervalsIntervalEnum23;
            /**
             * @type number
            */
            intervalCount: number;
            /**
             * @default 7
             * @type number | undefined
            */
            trialDays?: number;
            /**
             * @default "ACTIVE"
             * @type string | undefined
            */
            status?: IntervalsStatusEnum23;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @default false
         * @type boolean | undefined
        */
        highlight?: boolean;
        /**
         * @default false
         * @type boolean | undefined
        */
        default?: boolean;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: PlanStatusEnum23;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    };
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type number
    */
    amount: number;
    /**
     * @type string
    */
    paymentMethod: string;
    /**
     * @type object
    */
    boleto: {
        /**
         * @type string, uri
        */
        url: string;
        /**
         * @description Expiration date and time for the Boleto payment in ISO format.
         * @type string, date-time
        */
        expiresAt: string;
    };
    /**
     * @type string, date-time
    */
    dueDate: string;
    /**
     * @type string, date-time
    */
    issuedAt: string;
    paidAt?: (string | null);
    overdueAt?: (string | null);
    canceledAt?: (string | null);
    /**
     * @default "PENDING"
     * @type string | undefined
    */
    status?: GetInvoice200StatusEnum3;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
});

/**
 * @description Bad Request
*/
export type GetInvoice400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type GetInvoice500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type GetInvoiceQueryResponse = GetInvoice200;

export type GetInvoiceQuery = {
    Response: GetInvoice200;
    PathParams: GetInvoicePathParams;
    QueryParams: GetInvoiceQueryParams;
    HeaderParams: GetInvoiceHeaderParams;
    Errors: GetInvoice400 | GetInvoice500;
};