/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetOrganizationPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for organization
     * @type string, uuid
    */
    organizationId: string;
};

export type GetOrganizationQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type GetOrganization200StatusEnum = "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type GetOrganization200 = {
    /**
     * @description Unique identifier for organization
     * @type string, uuid
    */
    organizationId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: GetOrganization200StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type GetOrganization400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type GetOrganization500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type GetOrganizationQueryResponse = GetOrganization200;

export type GetOrganizationQuery = {
    Response: GetOrganization200;
    PathParams: GetOrganizationPathParams;
    QueryParams: GetOrganizationQueryParams;
    Errors: GetOrganization400 | GetOrganization500;
};