/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetPresignedUrlQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type GetPresignedUrlHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type GetPresignedUrlHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: GetPresignedUrlHeaderParamsAcceptLanguageEnum;
};

/**
 * @description OK
*/
export type GetPresignedUrl200 = {
    /**
     * @type string
    */
    fileName: string;
    /**
     * @type string
    */
    fileNameSigned: string;
};

/**
 * @description Bad Request
*/
export type GetPresignedUrl400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type GetPresignedUrl500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type GetPresignedUrlMutationRequestContextEnum = "USER_AVATAR" | "WORKSPACE_LOGO" | "ORGANIZATION_LOGO";

export type GetPresignedUrlMutationRequest = {
    /**
     * @type string
    */
    fileName: string;
    /**
     * @type string
    */
    context: GetPresignedUrlMutationRequestContextEnum;
};

export type GetPresignedUrlMutationResponse = GetPresignedUrl200;

export type GetPresignedUrlMutation = {
    Response: GetPresignedUrl200;
    Request: GetPresignedUrlMutationRequest;
    QueryParams: GetPresignedUrlQueryParams;
    HeaderParams: GetPresignedUrlHeaderParams;
    Errors: GetPresignedUrl400 | GetPresignedUrl500;
};