/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetProfileQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type GetProfileHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type GetProfileHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: GetProfileHeaderParamsAcceptLanguageEnum;
};

export type DocumentTypeEnum2 = "INDIVIDUAL" | "COMPANY";

export type GetProfile200LocalePreferenceEnum = "en" | "es" | "pt-BR";

export type GetProfile200StatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type GetProfile200 = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    googleProviderId?: (string | null);
    facebookProviderId?: (string | null);
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum2;
    } | null);
    /**
     * @type array | undefined
    */
    addresses?: {
        /**
         * @description Label used to identify the address (e.g., Home, Office).
         * @type string
        */
        title: string;
        /**
         * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
         * @type string
        */
        state: string;
        /**
         * @description City name.
         * @type string
        */
        city: string;
        /**
         * @description ZIP or postal code, containing digits only.
         * @type string
        */
        zipCode: string;
        /**
         * @description Neighborhood or district name.
         * @type string
        */
        neighborhood: string;
        /**
         * @description Street name.
         * @type string
        */
        street: string;
        /**
         * @description Street number.
         * @type string
        */
        number: string;
        /**
         * @type object
        */
        location: {
            /**
             * @description Latitude coordinate.
             * @type string
            */
            lat: string;
            /**
             * @description Longitude coordinate.
             * @type string
            */
            lng: string;
        };
        /**
         * @description Additional address details (optional).
        */
        complement?: (string | null);
        /**
         * @description Nearby reference point (optional).
        */
        landmark?: (string | null);
        /**
         * @description Indicates if this is the primary address.
         * @default false
         * @type boolean | undefined
        */
        main?: boolean;
    }[];
    avatar?: (string | null);
    localePreference?: (GetProfile200LocalePreferenceEnum | null);
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: GetProfile200StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type GetProfile400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type GetProfile401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type GetProfile500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type GetProfileQueryResponse = GetProfile200;

export type GetProfileQuery = {
    Response: GetProfile200;
    QueryParams: GetProfileQueryParams;
    HeaderParams: GetProfileHeaderParams;
    Errors: GetProfile400 | GetProfile401 | GetProfile500;
};