/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetPlanPathParams = {
	/**
	 * @description Unique identifier for plan
	 * @type string, uuid
	 */
	planId: string
}

export type GetPlanQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type GetPlanHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type GetPlanHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: GetPlanHeaderParamsAcceptLanguageEnum
}

export type IntervalsIntervalEnum25 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum25 = 'ACTIVE' | 'INACTIVE'

export type GetPlan200StatusEnum = 'ACTIVE' | 'INACTIVE'

/**
 * @description OK
 */
export type GetPlan200 = {
	/**
	 * @description Unique identifier for plan
	 * @type string, uuid
	 */
	planId: string
	/**
	 * @type string
	 */
	externalId: string
	/**
	 * @type string
	 */
	name: string
	/**
	 * @type string
	 */
	description: string
	/**
	 * @type array | undefined
	 */
	features?: {
		/**
		 * @description Unique identifier for planFeature
		 * @type string, uuid
		 */
		planFeatureId: string
		/**
		 * @type string
		 */
		description: string
		/**
		 * @type string
		 */
		feature: string
		/**
		 * @type object
		 */
		props: {
			/**
			 * @type number
			 */
			maxOrganizations: number
		}
		/**
		 * @type string, date-time
		 */
		createdAt: string
		/**
		 * @type string, date-time
		 */
		updatedAt: string
	}[]
	/**
	 * @type array | undefined
	 */
	intervals?: {
		/**
		 * @description Unique identifier for planInterval
		 * @type string, uuid
		 */
		planIntervalId: string
		/**
		 * @type string
		 */
		externalId: string
		/**
		 * @minLength 0
		 * @type number
		 */
		amount: number
		/**
		 * @type string
		 */
		interval: IntervalsIntervalEnum25
		/**
		 * @type number
		 */
		intervalCount: number
		/**
		 * @default 7
		 * @type number | undefined
		 */
		trialDays?: number
		/**
		 * @default "ACTIVE"
		 * @type string | undefined
		 */
		status?: IntervalsStatusEnum25
		/**
		 * @type string, date-time
		 */
		createdAt: string
		/**
		 * @type string, date-time
		 */
		updatedAt: string
	}[]
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	highlight?: boolean
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	default?: boolean
	/**
	 * @default "ACTIVE"
	 * @type string | undefined
	 */
	status?: GetPlan200StatusEnum
	deletedAt?: string | null
	/**
	 * @type string, date-time
	 */
	createdAt: string
	/**
	 * @type string, date-time
	 */
	updatedAt: string
}

/**
 * @description Bad Request
 */
export type GetPlan400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Not Found
 */
export type GetPlan404 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Internal Server
 */
export type GetPlan500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type GetPlanQueryResponse = GetPlan200

export type GetPlanQuery = {
	Response: GetPlan200
	PathParams: GetPlanPathParams
	QueryParams: GetPlanQueryParams
	HeaderParams: GetPlanHeaderParams
	Errors: GetPlan400 | GetPlan404 | GetPlan500
}
