/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetProfileQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type GetProfileHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type GetProfileHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: GetProfileHeaderParamsAcceptLanguageEnum;
};

export type ScopesKindEnum2 = "WORKSPACE" | "ORGANIZATION";

export type DocumentTypeEnum19 = "INDIVIDUAL" | "COMPANY";

export type GetProfile200LocalePreferenceEnum = "en" | "es" | "pt-BR";

export type GetProfile200StatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type GetProfile200 = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    /**
     * @type array
    */
    scopes: {
        /**
         * @type string
        */
        kind: ScopesKindEnum2;
        organizationId?: (string | null);
        /**
         * @type array
        */
        permissions: string[];
    }[];
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum19;
    } | null);
    avatar?: (string | null);
    localePreference?: (GetProfile200LocalePreferenceEnum | null);
    /**
     * @default "ONBOARDING"
     * @type string | undefined
    */
    status?: GetProfile200StatusEnum;
};

/**
 * @description Bad Request
*/
export type GetProfile400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type GetProfile401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type GetProfile500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type GetProfileQueryResponse = GetProfile200;

export type GetProfileQuery = {
    Response: GetProfile200;
    QueryParams: GetProfileQueryParams;
    HeaderParams: GetProfileHeaderParams;
    Errors: GetProfile400 | GetProfile401 | GetProfile500;
};