/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetRolePathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for role
     * @type string, uuid
    */
    roleId: string;
};

export type GetRoleQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type GetRoleHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type GetRoleHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: GetRoleHeaderParamsAcceptLanguageEnum;
};

export type DocumentTypeEnum18 = "INDIVIDUAL" | "COMPANY";

export type OrganizationsStatusEnum4 = "ACTIVE" | "INACTIVE";

export type GetRole200StatusEnum = "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type GetRole200 = {
    /**
     * @description Unique identifier for role
     * @type string, uuid
    */
    roleId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type array | undefined
    */
    organizations?: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @type string
        */
        name: string;
        email?: (string | null);
        phone?: ({
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        } | null);
        document?: ({
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum18;
        } | null);
        logo?: (string | null);
        domain?: (string | null);
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: OrganizationsStatusEnum4;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type array | undefined
    */
    permissions?: {
        /**
         * @description Unique identifier for permission
         * @type string, uuid
        */
        permissionId: string;
        /**
         * @type string
        */
        action: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type string
    */
    name: string;
    tags?: (string[] | null);
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: GetRole200StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type GetRole400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type GetRole500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type GetRoleQueryResponse = GetRole200;

export type GetRoleQuery = {
    Response: GetRole200;
    PathParams: GetRolePathParams;
    QueryParams: GetRoleQueryParams;
    HeaderParams: GetRoleHeaderParams;
    Errors: GetRole400 | GetRole500;
};