/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetUpcomingInvoicePathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
}

export type GetUpcomingInvoiceQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type GetUpcomingInvoiceHeaderParamsAcceptLanguageEnum =
	| 'en'
	| 'es'
	| 'pt-BR'

export type GetUpcomingInvoiceHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: GetUpcomingInvoiceHeaderParamsAcceptLanguageEnum
}

export type IntervalsIntervalEnum18 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum18 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum18 = 'ACTIVE' | 'INACTIVE'

export type GetUpcomingInvoice200StatusEnum = 'OPEN'

export type IntervalsIntervalEnum19 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum19 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum19 = 'ACTIVE' | 'INACTIVE'

export type GetUpcomingInvoice200StatusEnum2 = 'OPEN'

export type IntervalsIntervalEnum20 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum20 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum20 = 'ACTIVE' | 'INACTIVE'

export type GetUpcomingInvoice200StatusEnum3 = 'OPEN'

/**
 * @description OK
 */
export type GetUpcomingInvoice200 =
	| {
			/**
			 * @description Temporary identifier for an upcoming invoice that has not yet been generated.
			 * @type string
			 */
			invoiceId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum18
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum18
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum18
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type number
			 */
			amount: number
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type object
			 */
			card: {
				/**
				 * @description Token representing a securely stored payment card, typically returned by a payment provider.
				 * @type string
				 */
				token: string
				/**
				 * @description Masked card number for secure display.
				 * @type string
				 */
				number: string
				/**
				 * @description Name of the cardholder as printed on the card.
				 * @type string
				 */
				holderName: string
				/**
				 * @description Card expiration date in MM/YY format.
				 * @type string
				 */
				expirationDate: string
			}
			/**
			 * @type string, date-time
			 */
			dueDate: string
			/**
			 * @default "OPEN"
			 * @type string | undefined
			 */
			status?: GetUpcomingInvoice200StatusEnum
	  }
	| {
			/**
			 * @description Temporary identifier for an upcoming invoice that has not yet been generated.
			 * @type string
			 */
			invoiceId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum19
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum19
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum19
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type number
			 */
			amount: number
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type string, date-time
			 */
			dueDate: string
			/**
			 * @default "OPEN"
			 * @type string | undefined
			 */
			status?: GetUpcomingInvoice200StatusEnum2
	  }
	| {
			/**
			 * @description Temporary identifier for an upcoming invoice that has not yet been generated.
			 * @type string
			 */
			invoiceId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum20
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum20
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum20
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type number
			 */
			amount: number
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type string, date-time
			 */
			dueDate: string
			/**
			 * @default "OPEN"
			 * @type string | undefined
			 */
			status?: GetUpcomingInvoice200StatusEnum3
	  }

/**
 * @description Bad Request
 */
export type GetUpcomingInvoice400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Internal Server
 */
export type GetUpcomingInvoice500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type GetUpcomingInvoiceQueryResponse = GetUpcomingInvoice200

export type GetUpcomingInvoiceQuery = {
	Response: GetUpcomingInvoice200
	PathParams: GetUpcomingInvoicePathParams
	QueryParams: GetUpcomingInvoiceQueryParams
	HeaderParams: GetUpcomingInvoiceHeaderParams
	Errors: GetUpcomingInvoice400 | GetUpcomingInvoice500
}
