/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type InviteStatusEnum = "PENDING" | "ACCEPTED" | "CANCELLED";

export type Invite = {
    /**
     * @description Unique identifier for invite
     * @type string, uuid
    */
    inviteId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    /**
     * @type array
    */
    organizations: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @type array
        */
        roleIds: string[];
    }[];
    /**
     * @type string
    */
    token: string;
    /**
     * @type string
    */
    status: InviteStatusEnum;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};