/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type IntervalsIntervalEnum = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum = 'ACTIVE' | 'INACTIVE'

export type InvoiceStatusEnum = 'PENDING' | 'PAID' | 'OVERDUE' | 'CANCELED'

export type IntervalsIntervalEnum2 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum2 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum2 = 'ACTIVE' | 'INACTIVE'

export type InvoiceStatusEnum2 = 'PENDING' | 'PAID' | 'OVERDUE' | 'CANCELED'

export type IntervalsIntervalEnum3 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum3 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum3 = 'ACTIVE' | 'INACTIVE'

export type InvoiceStatusEnum3 = 'PENDING' | 'PAID' | 'OVERDUE' | 'CANCELED'

export type Invoice =
	| {
			/**
			 * @description Unique identifier for invoice
			 * @type string, uuid
			 */
			invoiceId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type string
			 */
			externalId: string
			/**
			 * @type string
			 */
			description: string
			/**
			 * @type number
			 */
			amount: number
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type object
			 */
			card: {
				/**
				 * @description Token representing a securely stored payment card, typically returned by a payment provider.
				 * @type string
				 */
				token: string
				/**
				 * @description Masked card number for secure display.
				 * @type string
				 */
				number: string
				/**
				 * @description Name of the cardholder as printed on the card.
				 * @type string
				 */
				holderName: string
				/**
				 * @description Card expiration date in MM/YY format.
				 * @type string
				 */
				expirationDate: string
			}
			/**
			 * @type string, date-time
			 */
			dueDate: string
			/**
			 * @type string, date-time
			 */
			issuedAt: string
			paidAt?: string | null
			overdueAt?: string | null
			canceledAt?: string | null
			/**
			 * @default "PENDING"
			 * @type string | undefined
			 */
			status?: InvoiceStatusEnum
			/**
			 * @type string, date-time
			 */
			createdAt: string
			/**
			 * @type string, date-time
			 */
			updatedAt: string
	  }
	| {
			/**
			 * @description Unique identifier for invoice
			 * @type string, uuid
			 */
			invoiceId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum2
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum2
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum2
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type string
			 */
			externalId: string
			/**
			 * @type string
			 */
			description: string
			/**
			 * @type number
			 */
			amount: number
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type object
			 */
			pix: {
				/**
				 * @description URL containing the Pix QR Code payload, used to initiate a payment.
				 * @type string, uri
				 */
				qrCodeUrl: string
				/**
				 * @description Expiration date and time for the Pix payment in ISO format.
				 * @type string, date-time
				 */
				expiresAt: string
			}
			/**
			 * @type string, date-time
			 */
			dueDate: string
			/**
			 * @type string, date-time
			 */
			issuedAt: string
			paidAt?: string | null
			overdueAt?: string | null
			canceledAt?: string | null
			/**
			 * @default "PENDING"
			 * @type string | undefined
			 */
			status?: InvoiceStatusEnum2
			/**
			 * @type string, date-time
			 */
			createdAt: string
			/**
			 * @type string, date-time
			 */
			updatedAt: string
	  }
	| {
			/**
			 * @description Unique identifier for invoice
			 * @type string, uuid
			 */
			invoiceId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description Unique identifier for subscription
			 * @type string, uuid
			 */
			subscriptionId: string
			/**
			 * @description Unique identifier for plan
			 * @type string, uuid
			 */
			planId: string
			/**
			 * @type object
			 */
			plan: {
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				name: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type array | undefined
				 */
				features?: {
					/**
					 * @description Unique identifier for planFeature
					 * @type string, uuid
					 */
					planFeatureId: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type string
					 */
					feature: string
					/**
					 * @type object
					 */
					props: {
						/**
						 * @type number
						 */
						maxOrganizations: number
					}
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @type array | undefined
				 */
				intervals?: {
					/**
					 * @description Unique identifier for planInterval
					 * @type string, uuid
					 */
					planIntervalId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @minLength 0
					 * @type number
					 */
					amount: number
					/**
					 * @type string
					 */
					interval: IntervalsIntervalEnum3
					/**
					 * @type number
					 */
					intervalCount: number
					/**
					 * @default 7
					 * @type number | undefined
					 */
					trialDays?: number
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: IntervalsStatusEnum3
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}[]
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				highlight?: boolean
				/**
				 * @default false
				 * @type boolean | undefined
				 */
				default?: boolean
				/**
				 * @default "ACTIVE"
				 * @type string | undefined
				 */
				status?: PlanStatusEnum3
				deletedAt?: string | null
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
			}
			/**
			 * @type string
			 */
			externalId: string
			/**
			 * @type string
			 */
			description: string
			/**
			 * @type number
			 */
			amount: number
			/**
			 * @type string
			 */
			paymentMethod: string
			/**
			 * @type object
			 */
			boleto: {
				/**
				 * @type string, uri
				 */
				url: string
				/**
				 * @description Expiration date and time for the Boleto payment in ISO format.
				 * @type string, date-time
				 */
				expiresAt: string
			}
			/**
			 * @type string, date-time
			 */
			dueDate: string
			/**
			 * @type string, date-time
			 */
			issuedAt: string
			paidAt?: string | null
			overdueAt?: string | null
			canceledAt?: string | null
			/**
			 * @default "PENDING"
			 * @type string | undefined
			 */
			status?: InvoiceStatusEnum3
			/**
			 * @type string, date-time
			 */
			createdAt: string
			/**
			 * @type string, date-time
			 */
			updatedAt: string
	  }
