/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ListRolesPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type ListRolesQueryParamsStatusEnum = "ACTIVE" | "INACTIVE";

export type ListRolesQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    status?: ListRolesQueryParamsStatusEnum;
    /**
     * @description Generic filter that can match against \n* name\n* status
     * @type string | undefined
    */
    filter?: string;
    cursor?: (string | null);
    /**
     * @type number | undefined
    */
    limit?: number;
};

export type ListRolesHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type ListRolesHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: ListRolesHeaderParamsAcceptLanguageEnum;
};

export type DocumentTypeEnum16 = "INDIVIDUAL" | "COMPANY";

export type OrganizationsStatusEnum2 = "ACTIVE" | "INACTIVE";

export type ValuesStatusEnum6 = "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type ListRoles200 = {
    /**
     * @type array
    */
    values: {
        /**
         * @description Unique identifier for role
         * @type string, uuid
        */
        roleId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @type array | undefined
        */
        organizations?: {
            /**
             * @description Unique identifier for organization
             * @type string, uuid
            */
            organizationId: string;
            /**
             * @description Unique identifier for workspace
             * @type string, uuid
            */
            workspaceId: string;
            /**
             * @type string
            */
            name: string;
            email?: (string | null);
            phone?: ({
                /**
                 * @description The ISO 3166-1 country code.
                 * @type string
                */
                iso: string;
                /**
                 * @description The international dialing code for the country, prefixed by the plus sign (+).
                 * @type string
                */
                ddi: string;
                /**
                 * @type string
                */
                number: string;
            } | null);
            document?: ({
                /**
                 * @type string
                */
                number: string;
                /**
                 * @type string
                */
                type: DocumentTypeEnum16;
            } | null);
            logo?: (string | null);
            domain?: (string | null);
            /**
             * @default "ACTIVE"
             * @type string | undefined
            */
            status?: OrganizationsStatusEnum2;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type array | undefined
        */
        permissions?: {
            /**
             * @description Unique identifier for permission
             * @type string, uuid
            */
            permissionId: string;
            /**
             * @type string
            */
            action: string;
            /**
             * @type string
            */
            name: string;
            /**
             * @type string
            */
            description: string;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type string
        */
        name: string;
        tags?: (string[] | null);
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: ValuesStatusEnum6;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @default [object Object]
     * @type object | undefined
    */
    meta?: {
        /**
         * @default null
        */
        nextCursor?: (string | null);
        /**
         * @default 0
         * @type number | undefined
        */
        limit?: number;
        /**
         * @default 0
         * @type number | undefined
        */
        total?: number;
    };
};

/**
 * @description Bad Request
*/
export type ListRoles400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type ListRoles500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type ListRolesQueryResponse = ListRoles200;

export type ListRolesQuery = {
    Response: ListRoles200;
    PathParams: ListRolesPathParams;
    QueryParams: ListRolesQueryParams;
    HeaderParams: ListRolesHeaderParams;
    Errors: ListRoles400 | ListRoles500;
};