/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ListPlansQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
    cursor?: (string | null);
    /**
     * @type number | undefined
    */
    limit?: number;
};

export type ListPlansHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type ListPlansHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: ListPlansHeaderParamsAcceptLanguageEnum;
};

export type IntervalsIntervalEnum2 = "DAY" | "WEEK" | "MONTH" | "YEAR";

export type IntervalsStatusEnum2 = "ACTIVE" | "INACTIVE";

export type ValuesStatusEnum5 = "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type ListPlans200 = {
    /**
     * @type array
    */
    values: {
        /**
         * @description Unique identifier for plan
         * @type string, uuid
        */
        planId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type array | undefined
        */
        features?: {
            /**
             * @description Unique identifier for planFeature
             * @type string, uuid
            */
            planFeatureId: string;
            /**
             * @type string
            */
            description: string;
            /**
             * @type string
            */
            feature: string;
            /**
             * @type object
            */
            props: {
                /**
                 * @type number
                */
                maxOrganizations: number;
            };
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @type array | undefined
        */
        intervals?: {
            /**
             * @description Unique identifier for planInterval
             * @type string, uuid
            */
            planIntervalId: string;
            /**
             * @type string
            */
            externalId: string;
            /**
             * @minLength 0
             * @type number
            */
            amount: number;
            /**
             * @type string
            */
            interval: IntervalsIntervalEnum2;
            /**
             * @default 1
             * @type number | undefined
            */
            intervalCount?: number;
            /**
             * @default 7
             * @type number | undefined
            */
            trialDays?: number;
            /**
             * @default "ACTIVE"
             * @type string | undefined
            */
            status?: IntervalsStatusEnum2;
            /**
             * @type string, date-time
            */
            createdAt: string;
            /**
             * @type string, date-time
            */
            updatedAt: string;
        }[];
        /**
         * @default false
         * @type boolean | undefined
        */
        highlight?: boolean;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: ValuesStatusEnum5;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @default [object Object]
     * @type object | undefined
    */
    meta?: {
        /**
         * @default null
        */
        nextCursor?: (string | null);
        /**
         * @default 0
         * @type number | undefined
        */
        limit?: number;
        /**
         * @default 0
         * @type number | undefined
        */
        total?: number;
    };
};

/**
 * @description Bad Request
*/
export type ListPlans400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type ListPlans500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type ListPlansQueryResponse = ListPlans200;

export type ListPlansQuery = {
    Response: ListPlans200;
    QueryParams: ListPlansQueryParams;
    HeaderParams: ListPlansHeaderParams;
    Errors: ListPlans400 | ListPlans500;
};