/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ListPermissionsQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type ListPermissionsHeaderParamsAcceptLanguageEnum =
	| 'en'
	| 'es'
	| 'pt-BR'

export type ListPermissionsHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: ListPermissionsHeaderParamsAcceptLanguageEnum
}

export type ListPermissions200PermissionIdEnum =
	| 'user:create'
	| 'user:read'
	| 'user:update'
	| 'user:delete'
	| 'workspace:manage'
	| 'workspace:create'
	| 'workspace:read'
	| 'workspace:update'
	| 'workspace:delete'
	| 'organization:manage'
	| 'organization:create'
	| 'organization:read'
	| 'organization:update'
	| 'organization:delete'
	| 'role:create'
	| 'role:read'
	| 'role:update'
	| 'role:delete'
	| 'invoice:read'
	| 'subscription:create'
	| 'subscription:read'
	| 'subscription:update:plan'
	| 'subscription:update:payment-method'
	| 'subscription:delete'

export type ListPermissions200SubjectEnum =
	| 'user'
	| 'workspace'
	| 'organization'
	| 'role'
	| 'invoice'
	| 'subscription'

/**
 * @description OK
 */
export type ListPermissions200 = {
	/**
	 * @type string
	 */
	permissionId: ListPermissions200PermissionIdEnum
	/**
	 * @type string
	 */
	subject: ListPermissions200SubjectEnum
	/**
	 * @description Depends on the subject. Common values include: read, write, update, delete.
	 * @type string
	 */
	action: string
	/**
	 * @description Human-readable name of the permission.
	 * @type string
	 */
	title: string
	/**
	 * @description Detailed explanation of what the permission allows within the system.
	 * @type string
	 */
	description: string
}[]

/**
 * @description Bad Request
 */
export type ListPermissions400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Internal Server
 */
export type ListPermissions500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type ListPermissionsQueryResponse = ListPermissions200

export type ListPermissionsQuery = {
	Response: ListPermissions200
	QueryParams: ListPermissionsQueryParams
	HeaderParams: ListPermissionsHeaderParams
	Errors: ListPermissions400 | ListPermissions500
}
