/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ListUsersPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type ListUsersQueryParamsStatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

export type ListUsersQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    status?: ListUsersQueryParamsStatusEnum;
    /**
     * @description Generic filter that can match against \n* name\n* email
     * @type string | undefined
    */
    filter?: string;
    cursor?: (string | null);
    /**
     * @type number | undefined
    */
    limit?: number;
};

export type ListUsersHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type ListUsersHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: ListUsersHeaderParamsAcceptLanguageEnum;
};

export type DocumentTypeEnum41 = "INDIVIDUAL" | "COMPANY";

export type ValuesLocalePreferenceEnum = "en" | "es" | "pt-BR";

export type ValuesStatusEnum7 = "ONBOARDING" | "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type ListUsers200 = {
    /**
     * @type array
    */
    values: {
        /**
         * @description Unique identifier for user
         * @type string, uuid
        */
        userId: string;
        workspaceId?: (string | null);
        googleProviderId?: (string | null);
        facebookProviderId?: (string | null);
        /**
         * @type string
        */
        name: string;
        /**
         * @type string, email
        */
        email: string;
        phone?: ({
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        } | null);
        birthday?: ((string | string) | null);
        document?: ({
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum41;
        } | null);
        /**
         * @type array | undefined
        */
        addresses?: {
            /**
             * @description Label used to identify the address (e.g., Home, Office).
             * @type string
            */
            title: string;
            /**
             * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
             * @type string
            */
            state: string;
            /**
             * @description City name.
             * @type string
            */
            city: string;
            /**
             * @description ZIP or postal code, containing digits only.
             * @type string
            */
            zipCode: string;
            /**
             * @description Neighborhood or district name.
             * @type string
            */
            neighborhood: string;
            /**
             * @description Street name.
             * @type string
            */
            street: string;
            /**
             * @description Street number.
             * @type string
            */
            number: string;
            /**
             * @type object
            */
            location: {
                /**
                 * @description Latitude coordinate.
                 * @type string
                */
                lat: string;
                /**
                 * @description Longitude coordinate.
                 * @type string
                */
                lng: string;
            };
            /**
             * @description Additional address details (optional).
            */
            complement?: (string | null);
            /**
             * @description Nearby reference point (optional).
            */
            landmark?: (string | null);
            /**
             * @description Indicates if this is the primary address.
             * @default false
             * @type boolean | undefined
            */
            main?: boolean;
        }[];
        avatar?: (string | null);
        localePreference?: (ValuesLocalePreferenceEnum | null);
        /**
         * @description A strong password.
         * @type string
        */
        password: string;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: ValuesStatusEnum7;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @default [object Object]
     * @type object | undefined
    */
    meta?: {
        /**
         * @default null
        */
        nextCursor?: (string | null);
        /**
         * @default 0
         * @type number | undefined
        */
        limit?: number;
        /**
         * @default 0
         * @type number | undefined
        */
        total?: number;
    };
};

/**
 * @description Bad Request
*/
export type ListUsers400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type ListUsers500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type ListUsersQueryResponse = ListUsers200;

export type ListUsersQuery = {
    Response: ListUsers200;
    PathParams: ListUsersPathParams;
    QueryParams: ListUsersQueryParams;
    HeaderParams: ListUsersHeaderParams;
    Errors: ListUsers400 | ListUsers500;
};