/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ListInvoicesPathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
}

export type ListInvoicesQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
	cursor: string | null
	/**
	 * @type number
	 */
	limit: number
}

export type ListInvoicesHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type ListInvoicesHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: ListInvoicesHeaderParamsAcceptLanguageEnum
}

export type IntervalsIntervalEnum15 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum15 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum15 = 'ACTIVE' | 'INACTIVE'

export type ValuesStatusEnum = 'PENDING' | 'PAID' | 'OVERDUE' | 'CANCELED'

export type IntervalsIntervalEnum16 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum16 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum16 = 'ACTIVE' | 'INACTIVE'

export type ValuesStatusEnum2 = 'PENDING' | 'PAID' | 'OVERDUE' | 'CANCELED'

export type IntervalsIntervalEnum17 = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'

export type IntervalsStatusEnum17 = 'ACTIVE' | 'INACTIVE'

export type PlanStatusEnum17 = 'ACTIVE' | 'INACTIVE'

export type ValuesStatusEnum3 = 'PENDING' | 'PAID' | 'OVERDUE' | 'CANCELED'

/**
 * @description OK
 */
export type ListInvoices200 = {
	/**
	 * @type array
	 */
	values: (
		| {
				/**
				 * @description Unique identifier for invoice
				 * @type string, uuid
				 */
				invoiceId: string
				/**
				 * @description Unique identifier for workspace
				 * @type string, uuid
				 */
				workspaceId: string
				/**
				 * @description Unique identifier for subscription
				 * @type string, uuid
				 */
				subscriptionId: string
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type object
				 */
				plan: {
					/**
					 * @description Unique identifier for plan
					 * @type string, uuid
					 */
					planId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @type string
					 */
					name: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type array | undefined
					 */
					features?: {
						/**
						 * @description Unique identifier for planFeature
						 * @type string, uuid
						 */
						planFeatureId: string
						/**
						 * @type string
						 */
						description: string
						/**
						 * @type string
						 */
						feature: string
						/**
						 * @type object
						 */
						props: {
							/**
							 * @type number
							 */
							maxOrganizations: number
						}
						/**
						 * @type string, date-time
						 */
						createdAt: string
						/**
						 * @type string, date-time
						 */
						updatedAt: string
					}[]
					/**
					 * @type array | undefined
					 */
					intervals?: {
						/**
						 * @description Unique identifier for planInterval
						 * @type string, uuid
						 */
						planIntervalId: string
						/**
						 * @type string
						 */
						externalId: string
						/**
						 * @minLength 0
						 * @type number
						 */
						amount: number
						/**
						 * @type string
						 */
						interval: IntervalsIntervalEnum15
						/**
						 * @type number
						 */
						intervalCount: number
						/**
						 * @default 7
						 * @type number | undefined
						 */
						trialDays?: number
						/**
						 * @default "ACTIVE"
						 * @type string | undefined
						 */
						status?: IntervalsStatusEnum15
						/**
						 * @type string, date-time
						 */
						createdAt: string
						/**
						 * @type string, date-time
						 */
						updatedAt: string
					}[]
					/**
					 * @default false
					 * @type boolean | undefined
					 */
					highlight?: boolean
					/**
					 * @default false
					 * @type boolean | undefined
					 */
					default?: boolean
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: PlanStatusEnum15
					deletedAt?: string | null
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type number
				 */
				amount: number
				/**
				 * @type string
				 */
				paymentMethod: string
				/**
				 * @type object
				 */
				card: {
					/**
					 * @description Token representing a securely stored payment card, typically returned by a payment provider.
					 * @type string
					 */
					token: string
					/**
					 * @description Masked card number for secure display.
					 * @type string
					 */
					number: string
					/**
					 * @description Name of the cardholder as printed on the card.
					 * @type string
					 */
					holderName: string
					/**
					 * @description Card expiration date in MM/YY format.
					 * @type string
					 */
					expirationDate: string
				}
				/**
				 * @type string, date-time
				 */
				dueDate: string
				/**
				 * @type string, date-time
				 */
				issuedAt: string
				paidAt?: string | null
				overdueAt?: string | null
				canceledAt?: string | null
				/**
				 * @default "PENDING"
				 * @type string | undefined
				 */
				status?: ValuesStatusEnum
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
		  }
		| {
				/**
				 * @description Unique identifier for invoice
				 * @type string, uuid
				 */
				invoiceId: string
				/**
				 * @description Unique identifier for workspace
				 * @type string, uuid
				 */
				workspaceId: string
				/**
				 * @description Unique identifier for subscription
				 * @type string, uuid
				 */
				subscriptionId: string
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type object
				 */
				plan: {
					/**
					 * @description Unique identifier for plan
					 * @type string, uuid
					 */
					planId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @type string
					 */
					name: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type array | undefined
					 */
					features?: {
						/**
						 * @description Unique identifier for planFeature
						 * @type string, uuid
						 */
						planFeatureId: string
						/**
						 * @type string
						 */
						description: string
						/**
						 * @type string
						 */
						feature: string
						/**
						 * @type object
						 */
						props: {
							/**
							 * @type number
							 */
							maxOrganizations: number
						}
						/**
						 * @type string, date-time
						 */
						createdAt: string
						/**
						 * @type string, date-time
						 */
						updatedAt: string
					}[]
					/**
					 * @type array | undefined
					 */
					intervals?: {
						/**
						 * @description Unique identifier for planInterval
						 * @type string, uuid
						 */
						planIntervalId: string
						/**
						 * @type string
						 */
						externalId: string
						/**
						 * @minLength 0
						 * @type number
						 */
						amount: number
						/**
						 * @type string
						 */
						interval: IntervalsIntervalEnum16
						/**
						 * @type number
						 */
						intervalCount: number
						/**
						 * @default 7
						 * @type number | undefined
						 */
						trialDays?: number
						/**
						 * @default "ACTIVE"
						 * @type string | undefined
						 */
						status?: IntervalsStatusEnum16
						/**
						 * @type string, date-time
						 */
						createdAt: string
						/**
						 * @type string, date-time
						 */
						updatedAt: string
					}[]
					/**
					 * @default false
					 * @type boolean | undefined
					 */
					highlight?: boolean
					/**
					 * @default false
					 * @type boolean | undefined
					 */
					default?: boolean
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: PlanStatusEnum16
					deletedAt?: string | null
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type number
				 */
				amount: number
				/**
				 * @type string
				 */
				paymentMethod: string
				/**
				 * @type object
				 */
				pix: {
					/**
					 * @description URL containing the Pix QR Code payload, used to initiate a payment.
					 * @type string, uri
					 */
					qrCodeUrl: string
					/**
					 * @description Expiration date and time for the Pix payment in ISO format.
					 * @type string, date-time
					 */
					expiresAt: string
				}
				/**
				 * @type string, date-time
				 */
				dueDate: string
				/**
				 * @type string, date-time
				 */
				issuedAt: string
				paidAt?: string | null
				overdueAt?: string | null
				canceledAt?: string | null
				/**
				 * @default "PENDING"
				 * @type string | undefined
				 */
				status?: ValuesStatusEnum2
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
		  }
		| {
				/**
				 * @description Unique identifier for invoice
				 * @type string, uuid
				 */
				invoiceId: string
				/**
				 * @description Unique identifier for workspace
				 * @type string, uuid
				 */
				workspaceId: string
				/**
				 * @description Unique identifier for subscription
				 * @type string, uuid
				 */
				subscriptionId: string
				/**
				 * @description Unique identifier for plan
				 * @type string, uuid
				 */
				planId: string
				/**
				 * @type object
				 */
				plan: {
					/**
					 * @description Unique identifier for plan
					 * @type string, uuid
					 */
					planId: string
					/**
					 * @type string
					 */
					externalId: string
					/**
					 * @type string
					 */
					name: string
					/**
					 * @type string
					 */
					description: string
					/**
					 * @type array | undefined
					 */
					features?: {
						/**
						 * @description Unique identifier for planFeature
						 * @type string, uuid
						 */
						planFeatureId: string
						/**
						 * @type string
						 */
						description: string
						/**
						 * @type string
						 */
						feature: string
						/**
						 * @type object
						 */
						props: {
							/**
							 * @type number
							 */
							maxOrganizations: number
						}
						/**
						 * @type string, date-time
						 */
						createdAt: string
						/**
						 * @type string, date-time
						 */
						updatedAt: string
					}[]
					/**
					 * @type array | undefined
					 */
					intervals?: {
						/**
						 * @description Unique identifier for planInterval
						 * @type string, uuid
						 */
						planIntervalId: string
						/**
						 * @type string
						 */
						externalId: string
						/**
						 * @minLength 0
						 * @type number
						 */
						amount: number
						/**
						 * @type string
						 */
						interval: IntervalsIntervalEnum17
						/**
						 * @type number
						 */
						intervalCount: number
						/**
						 * @default 7
						 * @type number | undefined
						 */
						trialDays?: number
						/**
						 * @default "ACTIVE"
						 * @type string | undefined
						 */
						status?: IntervalsStatusEnum17
						/**
						 * @type string, date-time
						 */
						createdAt: string
						/**
						 * @type string, date-time
						 */
						updatedAt: string
					}[]
					/**
					 * @default false
					 * @type boolean | undefined
					 */
					highlight?: boolean
					/**
					 * @default false
					 * @type boolean | undefined
					 */
					default?: boolean
					/**
					 * @default "ACTIVE"
					 * @type string | undefined
					 */
					status?: PlanStatusEnum17
					deletedAt?: string | null
					/**
					 * @type string, date-time
					 */
					createdAt: string
					/**
					 * @type string, date-time
					 */
					updatedAt: string
				}
				/**
				 * @type string
				 */
				externalId: string
				/**
				 * @type string
				 */
				description: string
				/**
				 * @type number
				 */
				amount: number
				/**
				 * @type string
				 */
				paymentMethod: string
				/**
				 * @type object
				 */
				boleto: {
					/**
					 * @type string, uri
					 */
					url: string
					/**
					 * @description Expiration date and time for the Boleto payment in ISO format.
					 * @type string, date-time
					 */
					expiresAt: string
				}
				/**
				 * @type string, date-time
				 */
				dueDate: string
				/**
				 * @type string, date-time
				 */
				issuedAt: string
				paidAt?: string | null
				overdueAt?: string | null
				canceledAt?: string | null
				/**
				 * @default "PENDING"
				 * @type string | undefined
				 */
				status?: ValuesStatusEnum3
				/**
				 * @type string, date-time
				 */
				createdAt: string
				/**
				 * @type string, date-time
				 */
				updatedAt: string
		  }
	)[]
	/**
	 * @default [object Object]
	 * @type object | undefined
	 */
	meta?: {
		/**
		 * @default null
		 */
		nextCursor?: string | null
		/**
		 * @default 0
		 * @type number | undefined
		 */
		limit?: number
		/**
		 * @default 0
		 * @type number | undefined
		 */
		total?: number
	}
}

/**
 * @description Bad Request
 */
export type ListInvoices400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Internal Server
 */
export type ListInvoices500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type ListInvoicesQueryResponse = ListInvoices200

export type ListInvoicesQuery = {
	Response: ListInvoices200
	PathParams: ListInvoicesPathParams
	QueryParams: ListInvoicesQueryParams
	HeaderParams: ListInvoicesHeaderParams
	Errors: ListInvoices400 | ListInvoices500
}
