/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ListInvoicesPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type ListInvoicesQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
    /**
     * @type string
    */
    cursor: string;
    /**
     * @type number
    */
    limit: number;
};

export type ValuesStatusEnum = "PENDING" | "PAID" | "OVERDUE" | "CANCELED";

export type ValuesStatusEnum2 = "PENDING" | "PAID" | "OVERDUE" | "CANCELED";

export type ValuesStatusEnum3 = "PENDING" | "PAID" | "OVERDUE" | "CANCELED";

/**
 * @description OK
*/
export type ListInvoices200 = {
    /**
     * @type array
    */
    values: ({
        /**
         * @description Unique identifier for invoice
         * @type string, uuid
        */
        invoiceId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @description Unique identifier for subscription
         * @type string, uuid
        */
        subscriptionId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type number
        */
        amount: number;
        /**
         * @type string
        */
        paymentMethod: string;
        /**
         * @type object
        */
        card: {
            /**
             * @description Token representing a securely stored payment card, typically returned by a payment provider.
             * @type string
            */
            token: string;
            /**
             * @description Masked card number for secure display.
             * @type string
            */
            number: string;
            /**
             * @description Name of the cardholder as printed on the card.
             * @type string
            */
            holderName: string;
            /**
             * @description Card expiration date in MM/YY format.
             * @type string
            */
            expirationDate: string;
        };
        /**
         * @type string, date-time
        */
        dueDate: string;
        /**
         * @type string, date-time
        */
        issuedAt: string;
        paidAt?: (string | null);
        overdueAt?: (string | null);
        canceledAt?: (string | null);
        /**
         * @default "PENDING"
         * @type string | undefined
        */
        status?: ValuesStatusEnum;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    } | {
        /**
         * @description Unique identifier for invoice
         * @type string, uuid
        */
        invoiceId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @description Unique identifier for subscription
         * @type string, uuid
        */
        subscriptionId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type number
        */
        amount: number;
        /**
         * @type string
        */
        paymentMethod: string;
        /**
         * @type object
        */
        pix: {
            /**
             * @description URL containing the Pix QR Code payload, used to initiate a payment.
             * @type string, uri
            */
            qrCodeUrl: string;
            /**
             * @description Expiration date and time for the Pix payment in ISO format.
             * @type string, date-time
            */
            expiresAt: string;
        };
        /**
         * @type string, date-time
        */
        dueDate: string;
        /**
         * @type string, date-time
        */
        issuedAt: string;
        paidAt?: (string | null);
        overdueAt?: (string | null);
        canceledAt?: (string | null);
        /**
         * @default "PENDING"
         * @type string | undefined
        */
        status?: ValuesStatusEnum2;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    } | {
        /**
         * @description Unique identifier for invoice
         * @type string, uuid
        */
        invoiceId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @description Unique identifier for subscription
         * @type string, uuid
        */
        subscriptionId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type number
        */
        amount: number;
        /**
         * @type string
        */
        paymentMethod: string;
        /**
         * @type object
        */
        boleto: {
            /**
             * @type string, uri
            */
            url: string;
            /**
             * @description Expiration date and time for the Boleto payment in ISO format.
             * @type string, date-time
            */
            expiresAt: string;
        };
        /**
         * @type string, date-time
        */
        dueDate: string;
        /**
         * @type string, date-time
        */
        issuedAt: string;
        paidAt?: (string | null);
        overdueAt?: (string | null);
        canceledAt?: (string | null);
        /**
         * @default "PENDING"
         * @type string | undefined
        */
        status?: ValuesStatusEnum3;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    })[];
    /**
     * @default [object Object]
     * @type object | undefined
    */
    meta?: {
        /**
         * @default null
        */
        nextCursor?: (string | null);
        /**
         * @default 0
         * @type number | undefined
        */
        limit?: number;
        /**
         * @default 0
         * @type number | undefined
        */
        total?: number;
    };
};

/**
 * @description Bad Request
*/
export type ListInvoices400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type ListInvoices500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type ListInvoicesQueryResponse = ListInvoices200;

export type ListInvoicesQuery = {
    Response: ListInvoices200;
    PathParams: ListInvoicesPathParams;
    QueryParams: ListInvoicesQueryParams;
    Errors: ListInvoices400 | ListInvoices500;
};