/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ListOrganizationsPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type ListOrganizationsQueryParamsStatusEnum = "ACTIVE" | "INACTIVE";

export type ListOrganizationsQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    status?: ListOrganizationsQueryParamsStatusEnum;
    /**
     * @description Generic filter that can match against \n* name\n* status
     * @type string | undefined
    */
    filter?: string;
    /**
     * @type string | undefined
    */
    cursor?: string;
    /**
     * @type number | undefined
    */
    limit?: number;
};

export type ValuesStatusEnum4 = "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type ListOrganizations200 = {
    /**
     * @type array
    */
    values: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: ValuesStatusEnum4;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @default [object Object]
     * @type object | undefined
    */
    meta?: {
        /**
         * @default null
        */
        nextCursor?: (string | null);
        /**
         * @default 0
         * @type number | undefined
        */
        limit?: number;
        /**
         * @default 0
         * @type number | undefined
        */
        total?: number;
    };
};

/**
 * @description Bad Request
*/
export type ListOrganizations400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type ListOrganizations500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type ListOrganizationsQueryResponse = ListOrganizations200;

export type ListOrganizationsQuery = {
    Response: ListOrganizations200;
    PathParams: ListOrganizationsPathParams;
    QueryParams: ListOrganizationsQueryParams;
    Errors: ListOrganizations400 | ListOrganizations500;
};