/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DocumentTypeEnum = "INDIVIDUAL" | "COMPANY";

export type OrganizationStatusEnum = "ACTIVE" | "INACTIVE";

export type Organization = {
    /**
     * @description Unique identifier for organization
     * @type string, uuid
    */
    organizationId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type string
    */
    name: string;
    email?: (string | null);
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum;
    } | null);
    logo?: (string | null);
    domain?: (string | null);
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: OrganizationStatusEnum;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};