/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Permission = {
    /**
     * @description Unique identifier for permission
     * @type string, uuid
    */
    permissionId: string;
    /**
     * @type string
    */
    action: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};