/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type IntervalsIntervalEnum = "DAY" | "WEEK" | "MONTH" | "YEAR";

export type IntervalsStatusEnum = "ACTIVE" | "INACTIVE";

export type PlanStatusEnum = "ACTIVE" | "INACTIVE";

export type Plan = {
    /**
     * @description Unique identifier for plan
     * @type string, uuid
    */
    planId: string;
    /**
     * @type string
    */
    externalId: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type array | undefined
    */
    features?: {
        /**
         * @description Unique identifier for planFeature
         * @type string, uuid
        */
        planFeatureId: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type string
        */
        feature: string;
        /**
         * @type object
        */
        props: {
            /**
             * @type number
            */
            maxOrganizations: number;
        };
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type array | undefined
    */
    intervals?: {
        /**
         * @description Unique identifier for planInterval
         * @type string, uuid
        */
        planIntervalId: string;
        /**
         * @type string
        */
        externalId: string;
        /**
         * @minLength 0
         * @type number
        */
        amount: number;
        /**
         * @type string
        */
        interval: IntervalsIntervalEnum;
        /**
         * @default 1
         * @type number | undefined
        */
        intervalCount?: number;
        /**
         * @default 7
         * @type number | undefined
        */
        trialDays?: number;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: IntervalsStatusEnum;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @default false
     * @type boolean | undefined
    */
    highlight?: boolean;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: PlanStatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};