/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ScopesKindEnum = "WORKSPACE" | "ORGANIZATION";

export type DocumentTypeEnum3 = "INDIVIDUAL" | "COMPANY";

export type ProfileLocalePreferenceEnum = "en" | "es" | "pt-BR";

export type ProfileStatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

export type Profile = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    /**
     * @type array
    */
    scopes: {
        /**
         * @type string
        */
        kind: ScopesKindEnum;
        organizationId?: (string | null);
        /**
         * @type array
        */
        permissions: string[];
    }[];
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum3;
    } | null);
    avatar?: (string | null);
    localePreference?: (ProfileLocalePreferenceEnum | null);
    /**
     * @default "ONBOARDING"
     * @type string | undefined
    */
    status?: ProfileStatusEnum;
};