/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResendInvitePathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
	/**
	 * @description Unique identifier for invite
	 * @type string, uuid
	 */
	inviteId: string
}

export type ResendInviteQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type ResendInviteHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type ResendInviteHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: ResendInviteHeaderParamsAcceptLanguageEnum
}

/**
 * @description Invite resent successfully.
 */
export type ResendInvite204 = any

/**
 * @description Bad Request
 */
export type ResendInvite400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Unauthorized
 */
export type ResendInvite401 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Not Found
 */
export type ResendInvite404 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Internal Server
 */
export type ResendInvite500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type ResendInviteMutationResponse = ResendInvite204

export type ResendInviteMutation = {
	Response: ResendInvite204
	PathParams: ResendInvitePathParams
	QueryParams: ResendInviteQueryParams
	HeaderParams: ResendInviteHeaderParams
	Errors: ResendInvite400 | ResendInvite401 | ResendInvite404 | ResendInvite500
}
