/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DocumentTypeEnum2 = "INDIVIDUAL" | "COMPANY";

export type OrganizationsStatusEnum = "ACTIVE" | "INACTIVE";

export type RoleStatusEnum = "ACTIVE" | "INACTIVE";

export type Role = {
    /**
     * @description Unique identifier for role
     * @type string, uuid
    */
    roleId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type array | undefined
    */
    organizations?: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @type string
        */
        name: string;
        email?: (string | null);
        phone?: ({
            /**
             * @description The ISO 3166-1 country code.
             * @type string
            */
            iso: string;
            /**
             * @description The international dialing code for the country, prefixed by the plus sign (+).
             * @type string
            */
            ddi: string;
            /**
             * @type string
            */
            number: string;
        } | null);
        document?: ({
            /**
             * @type string
            */
            number: string;
            /**
             * @type string
            */
            type: DocumentTypeEnum2;
        } | null);
        logo?: (string | null);
        domain?: (string | null);
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: OrganizationsStatusEnum;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type array | undefined
    */
    permissions?: {
        /**
         * @description Unique identifier for permission
         * @type string, uuid
        */
        permissionId: string;
        /**
         * @type string
        */
        action: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type string
    */
    name: string;
    tags?: (string[] | null);
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: RoleStatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};