/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type OrganizationsStatusEnum = "ACTIVE" | "INACTIVE";

export type RoleStatusEnum = "ACTIVE" | "INACTIVE";

export type Role = {
    /**
     * @description Unique identifier for role
     * @type string, uuid
    */
    roleId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type array | undefined
    */
    organizations?: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: OrganizationsStatusEnum;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type array | undefined
    */
    permissions?: {
        /**
         * @description Unique identifier for permission
         * @type string, uuid
        */
        permissionId: string;
        /**
         * @type string
        */
        action: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type string
    */
    name: string;
    tags?: (string[] | null);
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: RoleStatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};