/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SendForgotPasswordOTPQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type SendForgotPasswordOTPHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type SendForgotPasswordOTPHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: SendForgotPasswordOTPHeaderParamsAcceptLanguageEnum;
};

/**
 * @description Created
*/
export type SendForgotPasswordOTP201 = {
    /**
     * @description Unique identifier for otp
     * @type string, uuid
    */
    otpId: string;
};

/**
 * @description Bad Request
*/
export type SendForgotPasswordOTP400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Not Found
*/
export type SendForgotPasswordOTP404 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Conflict
*/
export type SendForgotPasswordOTP409 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type SendForgotPasswordOTP500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type SendForgotPasswordOTPMutationRequest = {
    /**
     * @type string, email
    */
    email: string;
};

export type SendForgotPasswordOTPMutationResponse = SendForgotPasswordOTP201;

export type SendForgotPasswordOTPMutation = {
    Response: SendForgotPasswordOTP201;
    Request: SendForgotPasswordOTPMutationRequest;
    QueryParams: SendForgotPasswordOTPQueryParams;
    HeaderParams: SendForgotPasswordOTPHeaderParams;
    Errors: SendForgotPasswordOTP400 | SendForgotPasswordOTP404 | SendForgotPasswordOTP409 | SendForgotPasswordOTP500;
};