/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SendInvitePathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type SendInviteQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type SendInviteHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type SendInviteHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: SendInviteHeaderParamsAcceptLanguageEnum;
};

/**
 * @description Invite sent successfully.
*/
export type SendInvite204 = any;

/**
 * @description Bad Request
*/
export type SendInvite400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type SendInvite401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Not Found
*/
export type SendInvite404 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Conflict
*/
export type SendInvite409 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type SendInvite500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type SendInviteMutationRequest = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    /**
     * @type array
    */
    organizations: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @type array
        */
        roleIds: string[];
    }[];
};

export type SendInviteMutationResponse = SendInvite204;

export type SendInviteMutation = {
    Response: SendInvite204;
    Request: SendInviteMutationRequest;
    PathParams: SendInvitePathParams;
    QueryParams: SendInviteQueryParams;
    HeaderParams: SendInviteHeaderParams;
    Errors: SendInvite400 | SendInvite401 | SendInvite404 | SendInvite409 | SendInvite500;
};