/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SendInvitePathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
}

export type SendInviteQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type SendInviteHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type SendInviteHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: SendInviteHeaderParamsAcceptLanguageEnum
}

/**
 * @description Invite sent successfully.
 */
export type SendInvite204 = any

/**
 * @description Bad Request
 */
export type SendInvite400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Unauthorized
 */
export type SendInvite401 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Not Found
 */
export type SendInvite404 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Conflict
 */
export type SendInvite409 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Internal Server
 */
export type SendInvite500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type DocumentTypeEnum14 = 'INDIVIDUAL' | 'COMPANY'

export type OrganizationStatusEnum4 = 'ACTIVE' | 'INACTIVE'

export type RolePermissionIdsEnum4 =
	| 'user:create'
	| 'user:read'
	| 'user:update'
	| 'user:delete'
	| 'workspace:manage'
	| 'workspace:create'
	| 'workspace:read'
	| 'workspace:update'
	| 'workspace:delete'
	| 'organization:manage'
	| 'organization:create'
	| 'organization:read'
	| 'organization:update'
	| 'organization:delete'
	| 'role:create'
	| 'role:read'
	| 'role:update'
	| 'role:delete'
	| 'invoice:read'
	| 'subscription:create'
	| 'subscription:read'
	| 'subscription:update:plan'
	| 'subscription:update:payment-method'
	| 'subscription:delete'

export type PermissionsPermissionIdEnum4 =
	| 'user:create'
	| 'user:read'
	| 'user:update'
	| 'user:delete'
	| 'workspace:manage'
	| 'workspace:create'
	| 'workspace:read'
	| 'workspace:update'
	| 'workspace:delete'
	| 'organization:manage'
	| 'organization:create'
	| 'organization:read'
	| 'organization:update'
	| 'organization:delete'
	| 'role:create'
	| 'role:read'
	| 'role:update'
	| 'role:delete'
	| 'invoice:read'
	| 'subscription:create'
	| 'subscription:read'
	| 'subscription:update:plan'
	| 'subscription:update:payment-method'
	| 'subscription:delete'

export type PermissionsSubjectEnum4 =
	| 'user'
	| 'workspace'
	| 'organization'
	| 'role'
	| 'invoice'
	| 'subscription'

export type RoleStatusEnum4 = 'ACTIVE' | 'INACTIVE'

export type SendInviteMutationRequest = {
	/**
	 * @type string
	 */
	name: string
	/**
	 * @type string, email
	 */
	email: string
	/**
	 * @type array
	 */
	organizations: {
		/**
		 * @description Unique identifier for organization
		 * @type string, uuid
		 */
		organizationId: string
		/**
		 * @type object
		 */
		organization: {
			/**
			 * @description Unique identifier for organization
			 * @type string, uuid
			 */
			organizationId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @type string
			 */
			name: string
			email?: string | null
			phone?: {
				/**
				 * @description The ISO 3166-1 country code.
				 * @type string
				 */
				iso: string
				/**
				 * @description The international dialing code for the country, prefixed by the plus sign (+).
				 * @type string
				 */
				ddi: string
				/**
				 * @type string
				 */
				number: string
			} | null
			document?: {
				/**
				 * @type string
				 */
				number: string
				/**
				 * @type string
				 */
				type: DocumentTypeEnum14
			} | null
			logo?: string | null
			domain?: string | null
			/**
			 * @type string
			 */
			status: OrganizationStatusEnum4
			deletedAt?: string | null
			/**
			 * @type string, date-time
			 */
			createdAt: string
			/**
			 * @type string, date-time
			 */
			updatedAt: string
		}
		/**
		 * @type array
		 */
		roleIds: string[]
		/**
		 * @type array
		 */
		role: {
			/**
			 * @description Unique identifier for role
			 * @type string, uuid
			 */
			roleId: string
			/**
			 * @description Unique identifier for workspace
			 * @type string, uuid
			 */
			workspaceId: string
			/**
			 * @description The IDs of the organizations to assign to the role
			 * @type array
			 */
			organizationIds: string[]
			/**
			 * @description The IDs of the permissions to assign to the role
			 * @type array
			 */
			permissionIds: RolePermissionIdsEnum4[]
			/**
			 * @type array | undefined
			 */
			permissions?: {
				/**
				 * @type string
				 */
				permissionId: PermissionsPermissionIdEnum4
				/**
				 * @type string
				 */
				subject: PermissionsSubjectEnum4
				/**
				 * @description Depends on the subject. Common values include: read, write, update, delete.
				 * @type string
				 */
				action: string
				/**
				 * @description Human-readable name of the permission.
				 * @type string
				 */
				title: string
				/**
				 * @description Detailed explanation of what the permission allows within the system.
				 * @type string
				 */
				description: string
			}[]
			/**
			 * @type string
			 */
			name: string
			/**
			 * @type array | undefined
			 */
			tags?: string[]
			/**
			 * @default "ACTIVE"
			 * @type string | undefined
			 */
			status?: RoleStatusEnum4
			deletedAt?: string | null
			/**
			 * @type string, date-time
			 */
			createdAt: string
			/**
			 * @type string, date-time
			 */
			updatedAt: string
		}[]
	}[]
}

export type SendInviteMutationResponse = SendInvite204

export type SendInviteMutation = {
	Response: SendInvite204
	Request: SendInviteMutationRequest
	PathParams: SendInvitePathParams
	QueryParams: SendInviteQueryParams
	HeaderParams: SendInviteHeaderParams
	Errors:
		| SendInvite400
		| SendInvite401
		| SendInvite404
		| SendInvite409
		| SendInvite500
}
