/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SendUpdatePhoneOTPQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type SendUpdatePhoneOTPHeaderParamsAcceptLanguageEnum =
	| 'en'
	| 'es'
	| 'pt-BR'

export type SendUpdatePhoneOTPHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: SendUpdatePhoneOTPHeaderParamsAcceptLanguageEnum
}

/**
 * @description Created
 */
export type SendUpdatePhoneOTP201 = {
	/**
	 * @description Unique identifier for otp
	 * @type string, uuid
	 */
	otpId: string
}

/**
 * @description Bad Request
 */
export type SendUpdatePhoneOTP400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Conflict
 */
export type SendUpdatePhoneOTP409 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Internal Server
 */
export type SendUpdatePhoneOTP500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type SendUpdatePhoneOTPMutationRequestChannelEnum = 'SMS' | 'WHATSAPP'

export type SendUpdatePhoneOTPMutationRequest = {
	/**
	 * @type string
	 */
	channel: SendUpdatePhoneOTPMutationRequestChannelEnum
	/**
	 * @type object
	 */
	phone: {
		/**
		 * @description The ISO 3166-1 country code.
		 * @type string
		 */
		iso: string
		/**
		 * @description The international dialing code for the country, prefixed by the plus sign (+).
		 * @type string
		 */
		ddi: string
		/**
		 * @type string
		 */
		number: string
	}
}

export type SendUpdatePhoneOTPMutationResponse = SendUpdatePhoneOTP201

export type SendUpdatePhoneOTPMutation = {
	Response: SendUpdatePhoneOTP201
	Request: SendUpdatePhoneOTPMutationRequest
	QueryParams: SendUpdatePhoneOTPQueryParams
	HeaderParams: SendUpdatePhoneOTPHeaderParams
	Errors: SendUpdatePhoneOTP400 | SendUpdatePhoneOTP409 | SendUpdatePhoneOTP500
}
