/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SignUpQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type SignUpHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type SignUpHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: SignUpHeaderParamsAcceptLanguageEnum
}

/**
 * @description Created
 */
export type SignUp201 = {
	/**
	 * @description JWT access token used to authenticate API requests.
	 * @type string
	 */
	accessToken: string
	/**
	 * @description JWT refresh token used to obtain new access tokens.
	 * @type string
	 */
	refreshToken: string
	/**
	 * @description Type of token returned. Usually \"Bearer\".
	 * @default "Bearer"
	 * @type string | undefined
	 */
	tokenType?: string
	/**
	 * @description Access token expiration time in hours.
	 * @type number
	 */
	expiresIn: number
}

/**
 * @description Bad Request
 */
export type SignUp400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Conflict
 */
export type SignUp409 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Internal Server
 */
export type SignUp500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type SignUpMutationRequest = {
	/**
	 * @type string
	 */
	name: string
	/**
	 * @type string, email
	 */
	email: string
	/**
	 * @description A strong password.
	 * @type string
	 */
	password: string
}

export type SignUpMutationResponse = SignUp201

export type SignUpMutation = {
	Response: SignUp201
	Request: SignUpMutationRequest
	QueryParams: SignUpQueryParams
	HeaderParams: SignUpHeaderParams
	Errors: SignUp400 | SignUp409 | SignUp500
}
