/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SignInQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type SignInHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type SignInHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: SignInHeaderParamsAcceptLanguageEnum
}

/**
 * @description OK
 */
export type SignIn200 = {
	/**
	 * @description JWT access token used to authenticate API requests.
	 * @type string
	 */
	accessToken: string
	/**
	 * @description JWT refresh token used to obtain new access tokens.
	 * @type string
	 */
	refreshToken: string
	/**
	 * @description Type of token returned. Usually \"Bearer\".
	 * @default "Bearer"
	 * @type string | undefined
	 */
	tokenType?: string
	/**
	 * @description Access token expiration time in hours.
	 * @type number
	 */
	expiresIn: number
}

/**
 * @description Bad Request
 */
export type SignIn400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Unauthorized
 */
export type SignIn401 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

/**
 * @description Internal Server
 */
export type SignIn500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type SignInMutationRequest = {
	/**
	 * @type string, email
	 */
	email: string
	/**
	 * @type string
	 */
	password: string
}

export type SignInMutationResponse = SignIn200

export type SignInMutation = {
	Response: SignIn200
	Request: SignInMutationRequest
	QueryParams: SignInQueryParams
	HeaderParams: SignInHeaderParams
	Errors: SignIn400 | SignIn401 | SignIn500
}
