/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SocialSignOnQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type SocialSignOnHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type SocialSignOnHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: SocialSignOnHeaderParamsAcceptLanguageEnum;
};

/**
 * @description OK
*/
export type SocialSignOn200 = {
    /**
     * @description JWT access token used to authenticate API requests.
     * @type string
    */
    accessToken: string;
    /**
     * @description JWT refresh token used to obtain new access tokens.
     * @type string
    */
    refreshToken: string;
    /**
     * @description Type of token returned. Usually \"Bearer\".
     * @default "Bearer"
     * @type string | undefined
    */
    tokenType?: string;
    /**
     * @description Access token expiration time in hours.
     * @type number
    */
    expiresIn: number;
};

/**
 * @description Bad Request
*/
export type SocialSignOn400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type SocialSignOn401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type SocialSignOn500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type SocialSignOnMutationRequestContextEnum = "GOOGLE" | "FACEBOOK";

export type SocialSignOnMutationRequest = {
    /**
     * @type string
    */
    context: SocialSignOnMutationRequestContextEnum;
    /**
     * @type string
    */
    providerToken: string;
};

export type SocialSignOnMutationResponse = SocialSignOn200;

export type SocialSignOnMutation = {
    Response: SocialSignOn200;
    Request: SocialSignOnMutationRequest;
    QueryParams: SocialSignOnQueryParams;
    HeaderParams: SocialSignOnHeaderParams;
    Errors: SocialSignOn400 | SocialSignOn401 | SocialSignOn500;
};