/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateProfilePhoneQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type UpdateProfilePhoneHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type UpdateProfilePhoneHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: UpdateProfilePhoneHeaderParamsAcceptLanguageEnum;
};

export type DocumentTypeEnum15 = "INDIVIDUAL" | "COMPANY";

export type UpdateProfilePhone200LocalePreferenceEnum = "en" | "es" | "pt-BR";

export type UpdateProfilePhone200StatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type UpdateProfilePhone200 = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    googleProviderId?: (string | null);
    facebookProviderId?: (string | null);
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum15;
    } | null);
    /**
     * @type array | undefined
    */
    addresses?: {
        /**
         * @description Label used to identify the address (e.g., Home, Office).
         * @type string
        */
        title: string;
        /**
         * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
         * @type string
        */
        state: string;
        /**
         * @description City name.
         * @type string
        */
        city: string;
        /**
         * @description ZIP or postal code, containing digits only.
         * @type string
        */
        zipCode: string;
        /**
         * @description Neighborhood or district name.
         * @type string
        */
        neighborhood: string;
        /**
         * @description Street name.
         * @type string
        */
        street: string;
        /**
         * @description Street number.
         * @type string
        */
        number: string;
        /**
         * @type object
        */
        location: {
            /**
             * @description Latitude coordinate.
             * @type string
            */
            lat: string;
            /**
             * @description Longitude coordinate.
             * @type string
            */
            lng: string;
        };
        /**
         * @description Additional address details (optional).
        */
        complement?: (string | null);
        /**
         * @description Nearby reference point (optional).
        */
        landmark?: (string | null);
        /**
         * @description Indicates if this is the primary address.
         * @default false
         * @type boolean | undefined
        */
        main?: boolean;
    }[];
    avatar?: (string | null);
    localePreference?: (UpdateProfilePhone200LocalePreferenceEnum | null);
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: UpdateProfilePhone200StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type UpdateProfilePhone400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type UpdateProfilePhone401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Forbidden
*/
export type UpdateProfilePhone403 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Not Found
*/
export type UpdateProfilePhone404 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Conflict
*/
export type UpdateProfilePhone409 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type UpdateProfilePhone500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type UpdateProfilePhoneMutationRequest = {
    /**
     * @type object
    */
    phone: {
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    };
    otpVerification: {
        /**
         * @description Unique identifier for otp
         * @type string, uuid
        */
        otpId: string;
        /**
         * @minLength 4
         * @maxLength 4
         * @type string
        */
        code: string;
    };
};

export type UpdateProfilePhoneMutationResponse = UpdateProfilePhone200;

export type UpdateProfilePhoneMutation = {
    Response: UpdateProfilePhone200;
    Request: UpdateProfilePhoneMutationRequest;
    QueryParams: UpdateProfilePhoneQueryParams;
    HeaderParams: UpdateProfilePhoneHeaderParams;
    Errors: UpdateProfilePhone400 | UpdateProfilePhone401 | UpdateProfilePhone403 | UpdateProfilePhone404 | UpdateProfilePhone409 | UpdateProfilePhone500;
};