/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateProfileQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type UpdateProfileHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type UpdateProfileHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: UpdateProfileHeaderParamsAcceptLanguageEnum;
};

export type ScopesKindEnum3 = "WORKSPACE" | "ORGANIZATION";

export type DocumentTypeEnum20 = "INDIVIDUAL" | "COMPANY";

export type UpdateProfile200LocalePreferenceEnum = "en" | "es" | "pt-BR";

export type UpdateProfile200StatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type UpdateProfile200 = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    /**
     * @type array
    */
    scopes: {
        /**
         * @type string
        */
        kind: ScopesKindEnum3;
        organizationId?: (string | null);
        /**
         * @type array
        */
        permissions: string[];
    }[];
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum20;
    } | null);
    avatar?: (string | null);
    localePreference?: (UpdateProfile200LocalePreferenceEnum | null);
    /**
     * @default "ONBOARDING"
     * @type string | undefined
    */
    status?: UpdateProfile200StatusEnum;
};

/**
 * @description Bad Request
*/
export type UpdateProfile400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type UpdateProfile401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type UpdateProfile500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type DocumentTypeEnum21 = "INDIVIDUAL" | "COMPANY";

export type UpdateProfileMutationRequestLocalePreferenceEnum = "en" | "es" | "pt-BR";

export type UpdateProfileMutationRequest = {
    /**
     * @type string | undefined
    */
    name?: string;
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum21;
    } | null);
    avatar?: (string | null);
    localePreference?: (UpdateProfileMutationRequestLocalePreferenceEnum | null);
};

export type UpdateProfileMutationResponse = UpdateProfile200;

export type UpdateProfileMutation = {
    Response: UpdateProfile200;
    Request: UpdateProfileMutationRequest;
    QueryParams: UpdateProfileQueryParams;
    HeaderParams: UpdateProfileHeaderParams;
    Errors: UpdateProfile400 | UpdateProfile401 | UpdateProfile500;
};