/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateUserPathParams = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type UpdateUserQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type UpdateUser200StatusEnum = "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type UpdateUser200 = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    avatar?: (string | null);
    socialGoogleId?: (string | null);
    socialFacebookId?: (string | null);
    /**
     * @minLength 8
     * @type string
    */
    password: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: UpdateUser200StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type UpdateUser400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type UpdateUser500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type UpdateUserMutationRequestStatusEnum = "ACTIVE" | "INACTIVE";

export type UpdateUserMutationRequest = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: UpdateUserMutationRequestStatusEnum;
    /**
     * @type array | undefined
    */
    organizations?: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @type array
        */
        roleIds: string[];
    }[];
};

export type UpdateUserMutationResponse = UpdateUser200;

export type UpdateUserMutation = {
    Response: UpdateUser200;
    Request: UpdateUserMutationRequest;
    PathParams: UpdateUserPathParams;
    QueryParams: UpdateUserQueryParams;
    Errors: UpdateUser400 | UpdateUser500;
};