/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateUserPathParams = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
};

export type UpdateUserQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type UpdateUserHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type UpdateUserHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: UpdateUserHeaderParamsAcceptLanguageEnum;
};

export type DocumentTypeEnum46 = "INDIVIDUAL" | "COMPANY";

export type UpdateUser200LocalePreferenceEnum = "en" | "es" | "pt-BR";

export type UpdateUser200StatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type UpdateUser200 = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    googleProviderExternalId?: (string | null);
    facebookProviderExternalId?: (string | null);
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum46;
    } | null);
    /**
     * @type array | undefined
    */
    addresses?: {
        /**
         * @description Label used to identify the address (e.g., Home, Office).
         * @type string
        */
        title: string;
        /**
         * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
         * @type string
        */
        state: string;
        /**
         * @description City name.
         * @type string
        */
        city: string;
        /**
         * @description ZIP or postal code, containing digits only.
         * @type string
        */
        zipCode: string;
        /**
         * @description Neighborhood or district name.
         * @type string
        */
        neighborhood: string;
        /**
         * @description Street name.
         * @type string
        */
        street: string;
        /**
         * @description Street number.
         * @type string
        */
        number: string;
        /**
         * @type object
        */
        location: {
            /**
             * @description Latitude coordinate.
             * @type string
            */
            lat: string;
            /**
             * @description Longitude coordinate.
             * @type string
            */
            lng: string;
        };
        /**
         * @description Additional address details (optional).
        */
        complement?: (string | null);
        /**
         * @description Nearby reference point (optional).
        */
        landmark?: (string | null);
        /**
         * @description Indicates if this is the primary address.
         * @default false
         * @type boolean | undefined
        */
        main?: boolean;
    }[];
    avatar?: (string | null);
    localePreference?: (UpdateUser200LocalePreferenceEnum | null);
    /**
     * @description A strong password.
     * @type string
    */
    password: string;
    /**
     * @default "ONBOARDING"
     * @type string | undefined
    */
    status?: UpdateUser200StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type UpdateUser400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type UpdateUser500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type UpdateUserMutationRequestStatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

export type UpdateUserMutationRequest = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default "ONBOARDING"
     * @type string | undefined
    */
    status?: UpdateUserMutationRequestStatusEnum;
    /**
     * @type array | undefined
    */
    organizations?: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @type array
        */
        roleIds: string[];
    }[];
};

export type UpdateUserMutationResponse = UpdateUser200;

export type UpdateUserMutation = {
    Response: UpdateUser200;
    Request: UpdateUserMutationRequest;
    PathParams: UpdateUserPathParams;
    QueryParams: UpdateUserQueryParams;
    HeaderParams: UpdateUserHeaderParams;
    Errors: UpdateUser400 | UpdateUser500;
};