/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateProfileEmailQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type UpdateProfileEmailHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type UpdateProfileEmailHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: UpdateProfileEmailHeaderParamsAcceptLanguageEnum;
};

export type ScopesKindEnum4 = "WORKSPACE" | "ORGANIZATION";

export type DocumentTypeEnum22 = "INDIVIDUAL" | "COMPANY";

export type UpdateProfileEmail200LocalePreferenceEnum = "en" | "es" | "pt-BR";

export type UpdateProfileEmail200StatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type UpdateProfileEmail200 = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    /**
     * @type array
    */
    scopes: {
        /**
         * @type string
        */
        kind: ScopesKindEnum4;
        organizationId?: (string | null);
        /**
         * @type array
        */
        permissions: string[];
    }[];
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum22;
    } | null);
    avatar?: (string | null);
    localePreference?: (UpdateProfileEmail200LocalePreferenceEnum | null);
    /**
     * @default "ONBOARDING"
     * @type string | undefined
    */
    status?: UpdateProfileEmail200StatusEnum;
};

/**
 * @description Bad Request
*/
export type UpdateProfileEmail400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Unauthorized
*/
export type UpdateProfileEmail401 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Forbidden
*/
export type UpdateProfileEmail403 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Not Found
*/
export type UpdateProfileEmail404 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Conflict
*/
export type UpdateProfileEmail409 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type UpdateProfileEmail500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type UpdateProfileEmailMutationRequest = {
    /**
     * @type string, email
    */
    email: string;
    otpVerification: {
        /**
         * @description Unique identifier for otp
         * @type string, uuid
        */
        otpId: string;
        /**
         * @minLength 4
         * @maxLength 4
         * @type string
        */
        code: string;
    };
};

export type UpdateProfileEmailMutationResponse = UpdateProfileEmail200;

export type UpdateProfileEmailMutation = {
    Response: UpdateProfileEmail200;
    Request: UpdateProfileEmailMutationRequest;
    QueryParams: UpdateProfileEmailQueryParams;
    HeaderParams: UpdateProfileEmailHeaderParams;
    Errors: UpdateProfileEmail400 | UpdateProfileEmail401 | UpdateProfileEmail403 | UpdateProfileEmail404 | UpdateProfileEmail409 | UpdateProfileEmail500;
};