/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateRolePathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for role
     * @type string, uuid
    */
    roleId: string;
};

export type UpdateRoleQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type OrganizationsStatusEnum5 = "ACTIVE" | "INACTIVE";

export type UpdateRole200StatusEnum = "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type UpdateRole200 = {
    /**
     * @description Unique identifier for role
     * @type string, uuid
    */
    roleId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type array | undefined
    */
    organizations?: {
        /**
         * @description Unique identifier for organization
         * @type string, uuid
        */
        organizationId: string;
        /**
         * @description Unique identifier for workspace
         * @type string, uuid
        */
        workspaceId: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @default "ACTIVE"
         * @type string | undefined
        */
        status?: OrganizationsStatusEnum5;
        deletedAt?: (string | null);
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type array | undefined
    */
    permissions?: {
        /**
         * @description Unique identifier for permission
         * @type string, uuid
        */
        permissionId: string;
        /**
         * @type string
        */
        action: string;
        /**
         * @type string
        */
        name: string;
        /**
         * @type string
        */
        description: string;
        /**
         * @type string, date-time
        */
        createdAt: string;
        /**
         * @type string, date-time
        */
        updatedAt: string;
    }[];
    /**
     * @type string
    */
    name: string;
    tags?: (string[] | null);
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: UpdateRole200StatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type UpdateRole400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type UpdateRole500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type UpdateRoleMutationRequest = {
    /**
     * @type string | undefined
    */
    name?: string;
    tags?: (string[] | null);
};

export type UpdateRoleMutationResponse = UpdateRole200;

export type UpdateRoleMutation = {
    Response: UpdateRole200;
    Request: UpdateRoleMutationRequest;
    PathParams: UpdateRolePathParams;
    QueryParams: UpdateRoleQueryParams;
    Errors: UpdateRole400 | UpdateRole500;
};