/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateRolePathParams = {
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
	/**
	 * @description Unique identifier for role
	 * @type string, uuid
	 */
	roleId: string
}

export type UpdateRoleQueryParams = {
	/**
	 * @description Comma-separated list of fields to return in the response.
	 * @type string | undefined
	 */
	fields?: string
}

export type UpdateRoleHeaderParamsAcceptLanguageEnum = 'en' | 'es' | 'pt-BR'

export type UpdateRoleHeaderParams = {
	/**
	 * @description Specifies the preferred language to be used in the response.
	 * @type string | undefined
	 */
	'Accept-Language'?: UpdateRoleHeaderParamsAcceptLanguageEnum
}

export type DocumentTypeEnum27 = 'INDIVIDUAL' | 'COMPANY'

export type OrganizationsStatusEnum5 = 'ACTIVE' | 'INACTIVE'

export type UpdateRole200PermissionIdsEnum =
	| 'user:create'
	| 'user:read'
	| 'user:update'
	| 'user:delete'
	| 'workspace:manage'
	| 'workspace:create'
	| 'workspace:read'
	| 'workspace:update'
	| 'workspace:delete'
	| 'organization:manage'
	| 'organization:create'
	| 'organization:read'
	| 'organization:update'
	| 'organization:delete'
	| 'role:create'
	| 'role:read'
	| 'role:update'
	| 'role:delete'
	| 'invoice:read'
	| 'subscription:create'
	| 'subscription:read'
	| 'subscription:update:plan'
	| 'subscription:update:payment-method'
	| 'subscription:delete'

export type PermissionsPermissionIdEnum8 =
	| 'user:create'
	| 'user:read'
	| 'user:update'
	| 'user:delete'
	| 'workspace:manage'
	| 'workspace:create'
	| 'workspace:read'
	| 'workspace:update'
	| 'workspace:delete'
	| 'organization:manage'
	| 'organization:create'
	| 'organization:read'
	| 'organization:update'
	| 'organization:delete'
	| 'role:create'
	| 'role:read'
	| 'role:update'
	| 'role:delete'
	| 'invoice:read'
	| 'subscription:create'
	| 'subscription:read'
	| 'subscription:update:plan'
	| 'subscription:update:payment-method'
	| 'subscription:delete'

export type PermissionsSubjectEnum8 =
	| 'user'
	| 'workspace'
	| 'organization'
	| 'role'
	| 'invoice'
	| 'subscription'

export type UpdateRole200StatusEnum = 'ACTIVE' | 'INACTIVE'

/**
 * @description OK
 */
export type UpdateRole200 = {
	/**
	 * @description Unique identifier for role
	 * @type string, uuid
	 */
	roleId: string
	/**
	 * @description Unique identifier for workspace
	 * @type string, uuid
	 */
	workspaceId: string
	/**
	 * @description The IDs of the organizations to assign to the role
	 * @type array
	 */
	organizationIds: string[]
	/**
	 * @type array | undefined
	 */
	organizations?: {
		/**
		 * @description Unique identifier for organization
		 * @type string, uuid
		 */
		organizationId: string
		/**
		 * @description Unique identifier for workspace
		 * @type string, uuid
		 */
		workspaceId: string
		/**
		 * @type string
		 */
		name: string
		email?: string | null
		phone?: {
			/**
			 * @description The ISO 3166-1 country code.
			 * @type string
			 */
			iso: string
			/**
			 * @description The international dialing code for the country, prefixed by the plus sign (+).
			 * @type string
			 */
			ddi: string
			/**
			 * @type string
			 */
			number: string
		} | null
		document?: {
			/**
			 * @type string
			 */
			number: string
			/**
			 * @type string
			 */
			type: DocumentTypeEnum27
		} | null
		logo?: string | null
		domain?: string | null
		/**
		 * @type string
		 */
		status: OrganizationsStatusEnum5
		deletedAt?: string | null
		/**
		 * @type string, date-time
		 */
		createdAt: string
		/**
		 * @type string, date-time
		 */
		updatedAt: string
	}[]
	/**
	 * @description The IDs of the permissions to assign to the role
	 * @type array
	 */
	permissionIds: UpdateRole200PermissionIdsEnum[]
	/**
	 * @type array | undefined
	 */
	permissions?: {
		/**
		 * @type string
		 */
		permissionId: PermissionsPermissionIdEnum8
		/**
		 * @type string
		 */
		subject: PermissionsSubjectEnum8
		/**
		 * @description Depends on the subject. Common values include: read, write, update, delete.
		 * @type string
		 */
		action: string
		/**
		 * @description Human-readable name of the permission.
		 * @type string
		 */
		title: string
		/**
		 * @description Detailed explanation of what the permission allows within the system.
		 * @type string
		 */
		description: string
	}[]
	/**
	 * @type string
	 */
	name: string
	/**
	 * @type array | undefined
	 */
	tags?: string[]
	/**
	 * @default "ACTIVE"
	 * @type string | undefined
	 */
	status?: UpdateRole200StatusEnum
	deletedAt?: string | null
	/**
	 * @type string, date-time
	 */
	createdAt: string
	/**
	 * @type string, date-time
	 */
	updatedAt: string
}

/**
 * @description Bad Request
 */
export type UpdateRole400 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type array
	 */
	issues: {
		[key: string]: string
	}[]
}

/**
 * @description Internal Server
 */
export type UpdateRole500 = {
	/**
	 * @type number
	 */
	statusCode: number
	/**
	 * @type string
	 */
	error: string
	/**
	 * @type string
	 */
	message: string
	/**
	 * @type object | undefined
	 */
	metadata?: {
		[key: string]: string
	}
}

export type UpdateRoleMutationRequest = {
	/**
	 * @type string | undefined
	 */
	name?: string
	/**
	 * @type array | undefined
	 */
	tags?: string[]
}

export type UpdateRoleMutationResponse = UpdateRole200

export type UpdateRoleMutation = {
	Response: UpdateRole200
	Request: UpdateRoleMutationRequest
	PathParams: UpdateRolePathParams
	QueryParams: UpdateRoleQueryParams
	HeaderParams: UpdateRoleHeaderParams
	Errors: UpdateRole400 | UpdateRole500
}
