/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateOrganizationPathParams = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @description Unique identifier for organization
     * @type string, uuid
    */
    organizationId: string;
};

export type UpdateOrganizationQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type UpdateOrganizationHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type UpdateOrganizationHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: UpdateOrganizationHeaderParamsAcceptLanguageEnum;
};

export type DocumentTypeEnum11 = "INDIVIDUAL" | "COMPANY";

export type UpdateOrganization200StatusEnum = "ACTIVE" | "INACTIVE";

/**
 * @description OK
*/
export type UpdateOrganization200 = {
    /**
     * @description Unique identifier for organization
     * @type string, uuid
    */
    organizationId: string;
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    /**
     * @type string
    */
    name: string;
    email?: (string | null);
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum11;
    } | null);
    logo?: (string | null);
    domain?: (string | null);
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: UpdateOrganization200StatusEnum;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};

/**
 * @description Bad Request
*/
export type UpdateOrganization400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Internal Server
*/
export type UpdateOrganization500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type UpdateOrganizationMutationRequestStatusEnum = "ACTIVE" | "INACTIVE";

export type UpdateOrganizationMutationRequest = {
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: UpdateOrganizationMutationRequestStatusEnum;
};

export type UpdateOrganizationMutationResponse = UpdateOrganization200;

export type UpdateOrganizationMutation = {
    Response: UpdateOrganization200;
    Request: UpdateOrganizationMutationRequest;
    PathParams: UpdateOrganizationPathParams;
    QueryParams: UpdateOrganizationQueryParams;
    HeaderParams: UpdateOrganizationHeaderParams;
    Errors: UpdateOrganization400 | UpdateOrganization500;
};