/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UserStatusEnum = "ACTIVE" | "INACTIVE";

export type User = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    avatar?: (string | null);
    socialGoogleId?: (string | null);
    socialFacebookId?: (string | null);
    /**
     * @minLength 8
     * @type string
    */
    password: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: UserStatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};