/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DocumentTypeEnum6 = "INDIVIDUAL" | "COMPANY";

export type UserLocalePreferenceEnum = "en" | "es" | "pt-BR";

export type UserStatusEnum = "ONBOARDING" | "ACTIVE" | "INACTIVE";

export type User = {
    /**
     * @description Unique identifier for user
     * @type string, uuid
    */
    userId: string;
    workspaceId?: (string | null);
    googleProviderId?: (string | null);
    facebookProviderId?: (string | null);
    /**
     * @type string
    */
    name: string;
    /**
     * @type string, email
    */
    email: string;
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    birthday?: ((string | string) | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum6;
    } | null);
    /**
     * @type array | undefined
    */
    addresses?: {
        /**
         * @description Label used to identify the address (e.g., Home, Office).
         * @type string
        */
        title: string;
        /**
         * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
         * @type string
        */
        state: string;
        /**
         * @description City name.
         * @type string
        */
        city: string;
        /**
         * @description ZIP or postal code, containing digits only.
         * @type string
        */
        zipCode: string;
        /**
         * @description Neighborhood or district name.
         * @type string
        */
        neighborhood: string;
        /**
         * @description Street name.
         * @type string
        */
        street: string;
        /**
         * @description Street number.
         * @type string
        */
        number: string;
        /**
         * @type object
        */
        location: {
            /**
             * @description Latitude coordinate.
             * @type string
            */
            lat: string;
            /**
             * @description Longitude coordinate.
             * @type string
            */
            lng: string;
        };
        /**
         * @description Additional address details (optional).
        */
        complement?: (string | null);
        /**
         * @description Nearby reference point (optional).
        */
        landmark?: (string | null);
        /**
         * @description Indicates if this is the primary address.
         * @default false
         * @type boolean | undefined
        */
        main?: boolean;
    }[];
    avatar?: (string | null);
    localePreference?: (UserLocalePreferenceEnum | null);
    /**
     * @description A strong password.
     * @type string
    */
    password: string;
    /**
     * @default "ACTIVE"
     * @type string | undefined
    */
    status?: UserStatusEnum;
    deletedAt?: (string | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};