/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ValidateOTPPathParams = {
    /**
     * @description Unique identifier for otp
     * @type string, uuid
    */
    otpId: string;
};

export type ValidateOTPQueryParams = {
    /**
     * @description Comma-separated list of fields to return in the response.
     * @type string | undefined
    */
    fields?: string;
};

export type ValidateOTPHeaderParamsAcceptLanguageEnum = "en" | "es" | "pt-BR";

export type ValidateOTPHeaderParams = {
    /**
     * @description Specifies the preferred language to be used in the response.
     * @type string | undefined
    */
    "Accept-Language"?: ValidateOTPHeaderParamsAcceptLanguageEnum;
};

/**
 * @description OTP has been successfully validated
*/
export type ValidateOTP204 = any;

/**
 * @description Bad Request
*/
export type ValidateOTP400 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type array
    */
    issues: {
        [key: string]: string;
    }[];
};

/**
 * @description Forbidden
*/
export type ValidateOTP403 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Not Found
*/
export type ValidateOTP404 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Conflict
*/
export type ValidateOTP409 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * @description Internal Server
*/
export type ValidateOTP500 = {
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string
    */
    error: string;
    /**
     * @type string
    */
    message: string;
    /**
     * @type object | undefined
    */
    metadata?: {
        [key: string]: string;
    };
};

export type ValidateOTPMutationRequestContextEnum = "PASSWORD_LESS" | "FORGOT_PASSWORD" | "UPDATE_EMAIL" | "UPDATE_PHONE";

export type ValidateOTPMutationRequest = {
    /**
     * @description Business scenario for which the OTP is generated
     * @type string
    */
    context: ValidateOTPMutationRequestContextEnum;
    /**
     * @description Target recipient of the OTP (email or phone number)
     * @type string
    */
    recipient: string;
    /**
     * @description One-time password code sent to the recipient
     * @type string
    */
    code: string;
};

export type ValidateOTPMutationResponse = ValidateOTP204;

export type ValidateOTPMutation = {
    Response: ValidateOTP204;
    Request: ValidateOTPMutationRequest;
    PathParams: ValidateOTPPathParams;
    QueryParams: ValidateOTPQueryParams;
    HeaderParams: ValidateOTPHeaderParams;
    Errors: ValidateOTP400 | ValidateOTP403 | ValidateOTP404 | ValidateOTP409 | ValidateOTP500;
};