/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DocumentTypeEnum7 = "INDIVIDUAL" | "COMPANY";

export type LocaleDefaultLocaleEnum = "en" | "es" | "pt-BR";

export type LocaleAvailableLocalesEnum = "en" | "es" | "pt-BR";

export type WorkspaceStatusEnum = "TRIAL" | "ACTIVE" | "INACTIVE";

export type Workspace = {
    /**
     * @description Unique identifier for workspace
     * @type string, uuid
    */
    workspaceId: string;
    recurrenceExternalId?: (string | null);
    /**
     * @type string
    */
    name: string;
    email?: (string | null);
    phone?: ({
        /**
         * @description The ISO 3166-1 country code.
         * @type string
        */
        iso: string;
        /**
         * @description The international dialing code for the country, prefixed by the plus sign (+).
         * @type string
        */
        ddi: string;
        /**
         * @type string
        */
        number: string;
    } | null);
    document?: ({
        /**
         * @type string
        */
        number: string;
        /**
         * @type string
        */
        type: DocumentTypeEnum7;
    } | null);
    address?: ({
        /**
         * @description Two-letter state code following the ISO 3166-2 standard for country subdivisions.
         * @type string
        */
        state: string;
        /**
         * @description City name.
         * @type string
        */
        city: string;
        /**
         * @description ZIP or postal code, containing digits only.
         * @type string
        */
        zipCode: string;
        /**
         * @description Neighborhood or district name.
         * @type string
        */
        neighborhood: string;
        /**
         * @description Street name.
         * @type string
        */
        street: string;
        /**
         * @description Street number.
         * @type string
        */
        number: string;
        /**
         * @type object
        */
        location: {
            /**
             * @description Latitude coordinate.
             * @type string
            */
            lat: string;
            /**
             * @description Longitude coordinate.
             * @type string
            */
            lng: string;
        };
        /**
         * @description Additional address details (optional).
        */
        complement?: (string | null);
        /**
         * @description Nearby reference point (optional).
        */
        landmark?: (string | null);
    } | null);
    logo?: (string | null);
    domain?: (string | null);
    locale?: ({
        /**
         * @type string
        */
        defaultLocale: LocaleDefaultLocaleEnum;
        /**
         * @type array | undefined
        */
        availableLocales?: LocaleAvailableLocalesEnum[];
    } | null);
    trialEndsAt?: (string | null);
    /**
     * @default "TRIAL"
     * @type string | undefined
    */
    status?: WorkspaceStatusEnum;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};