service: lambda-service-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

custom:
  dotenv:
    path: ../../.env
    logging: false

plugins:
  - serverless-dotenv-plugin

resources:
  Resources:
    LambdaServiceExampleQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: lambda-service-example-queue

functions:
  service:
    handler: dist/main.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - LambdaServiceExampleQueue
              - Arn
          batchSize: 1
          maximumBatchingWindow: 0
