/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { AcceptInviteMutationRequest, AcceptInviteMutationResponse, AcceptInvitePathParams, AcceptInviteQueryParams, AcceptInviteHeaderParams, AcceptInvite400, AcceptInvite401, AcceptInvite404, AcceptInvite500 } from "../types/AcceptInvite";

function getAcceptInviteUrl({ workspaceId, inviteId }: { workspaceId: AcceptInvitePathParams["workspaceId"]; inviteId: AcceptInvitePathParams["inviteId"] }) {
  const res = { method: 'POST', url: `http://localhost:4000/v1/workspaces/${workspaceId}/invites/${inviteId}/accept` as const }  
  return res
}

/**
 * @description Accepts a pending invite and creates the user account.
 * @summary Accept Invite
 * {@link /v1/workspaces/:workspaceId/invites/:inviteId/accept}
 */
export async function acceptInvite({ workspaceId, inviteId }: { workspaceId: AcceptInvitePathParams["workspaceId"]; inviteId: AcceptInvitePathParams["inviteId"] }, data: AcceptInviteMutationRequest, params?: AcceptInviteQueryParams, headers?: AcceptInviteHeaderParams, config: Partial<RequestConfig<AcceptInviteMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AcceptInviteMutationResponse, ResponseErrorConfig<AcceptInvite400 | AcceptInvite401 | AcceptInvite404 | AcceptInvite500>, AcceptInviteMutationRequest>({ method : "POST", url : getAcceptInviteUrl({ workspaceId, inviteId }).url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}