/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	CancelInviteMutationResponse,
	CancelInvitePathParams,
	CancelInviteQueryParams,
	CancelInviteHeaderParams,
	CancelInvite400,
	CancelInvite404,
	CancelInvite500,
} from '../types/CancelInvite'

function getCancelInviteUrl({
	workspaceId,
	inviteId,
}: {
	workspaceId: CancelInvitePathParams['workspaceId']
	inviteId: CancelInvitePathParams['inviteId']
}) {
	const res = {
		method: 'DELETE',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/invites/${inviteId}` as const,
	}
	return res
}

/**
 * @description Cancels a pending invite.
 * @summary Cancel Invite
 * {@link /v1/workspaces/:workspaceId/invites/:inviteId}
 */
export async function cancelInvite(
	{
		workspaceId,
		inviteId,
	}: {
		workspaceId: CancelInvitePathParams['workspaceId']
		inviteId: CancelInvitePathParams['inviteId']
	},
	params?: CancelInviteQueryParams,
	headers?: CancelInviteHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		CancelInviteMutationResponse,
		ResponseErrorConfig<CancelInvite400 | CancelInvite404 | CancelInvite500>,
		unknown
	>({
		method: 'DELETE',
		url: getCancelInviteUrl({
			workspaceId,
			inviteId,
		}).url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
