/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	ChangeSubscriptionPlanMutationRequest,
	ChangeSubscriptionPlanMutationResponse,
	ChangeSubscriptionPlanPathParams,
	ChangeSubscriptionPlanQueryParams,
	ChangeSubscriptionPlanHeaderParams,
	ChangeSubscriptionPlan400,
	ChangeSubscriptionPlan500,
} from '../types/ChangeSubscriptionPlan'

function getChangeSubscriptionPlanUrl({
	workspaceId,
	subscriptionId,
}: {
	workspaceId: ChangeSubscriptionPlanPathParams['workspaceId']
	subscriptionId: ChangeSubscriptionPlanPathParams['subscriptionId']
}) {
	const res = {
		method: 'POST',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/subscriptions/${subscriptionId}/plan` as const,
	}
	return res
}

/**
 * @description Updates plan of an existing subscription by its ID.
 * @summary Change Subscription Plan
 * {@link /v1/workspaces/:workspaceId/subscriptions/:subscriptionId/plan}
 */
export async function changeSubscriptionPlan(
	{
		workspaceId,
		subscriptionId,
	}: {
		workspaceId: ChangeSubscriptionPlanPathParams['workspaceId']
		subscriptionId: ChangeSubscriptionPlanPathParams['subscriptionId']
	},
	data: ChangeSubscriptionPlanMutationRequest,
	params?: ChangeSubscriptionPlanQueryParams,
	headers?: ChangeSubscriptionPlanHeaderParams,
	config: Partial<RequestConfig<ChangeSubscriptionPlanMutationRequest>> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const requestData = data

	const res = await request<
		ChangeSubscriptionPlanMutationResponse,
		ResponseErrorConfig<ChangeSubscriptionPlan400 | ChangeSubscriptionPlan500>,
		ChangeSubscriptionPlanMutationRequest
	>({
		method: 'POST',
		url: getChangeSubscriptionPlanUrl({
			workspaceId,
			subscriptionId,
		}).url.toString(),
		params,
		data: requestData,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
