/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { ChangeSubscriptionPaymentMethodMutationRequest, ChangeSubscriptionPaymentMethodMutationResponse, ChangeSubscriptionPaymentMethodPathParams, ChangeSubscriptionPaymentMethodQueryParams, ChangeSubscriptionPaymentMethodHeaderParams, ChangeSubscriptionPaymentMethod400, ChangeSubscriptionPaymentMethod500 } from "../types/ChangeSubscriptionPaymentMethod";

function getChangeSubscriptionPaymentMethodUrl({ workspaceId, subscriptionId }: { workspaceId: ChangeSubscriptionPaymentMethodPathParams["workspaceId"]; subscriptionId: ChangeSubscriptionPaymentMethodPathParams["subscriptionId"] }) {
  const res = { method: 'POST', url: `http://localhost:4000/v1/workspaces/${workspaceId}/subscriptions/${subscriptionId}/payment-method` as const }  
  return res
}

/**
 * @description Updates payment method of an existing subscription by its ID.
 * @summary Change Subscription Payment Method
 * {@link /v1/workspaces/:workspaceId/subscriptions/:subscriptionId/payment-method}
 */
export async function changeSubscriptionPaymentMethod({ workspaceId, subscriptionId }: { workspaceId: ChangeSubscriptionPaymentMethodPathParams["workspaceId"]; subscriptionId: ChangeSubscriptionPaymentMethodPathParams["subscriptionId"] }, data?: ChangeSubscriptionPaymentMethodMutationRequest, params?: ChangeSubscriptionPaymentMethodQueryParams, headers?: ChangeSubscriptionPaymentMethodHeaderParams, config: Partial<RequestConfig<ChangeSubscriptionPaymentMethodMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChangeSubscriptionPaymentMethodMutationResponse, ResponseErrorConfig<ChangeSubscriptionPaymentMethod400 | ChangeSubscriptionPaymentMethod500>, ChangeSubscriptionPaymentMethodMutationRequest>({ method : "POST", url : getChangeSubscriptionPaymentMethodUrl({ workspaceId, subscriptionId }).url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}