/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	CreateRoleMutationRequest,
	CreateRoleMutationResponse,
	CreateRolePathParams,
	CreateRoleQueryParams,
	CreateRoleHeaderParams,
	CreateRole400,
	CreateRole500,
} from '../types/CreateRole'

function getCreateRoleUrl({
	workspaceId,
}: {
	workspaceId: CreateRolePathParams['workspaceId']
}) {
	const res = {
		method: 'POST',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/roles` as const,
	}
	return res
}

/**
 * @description Creates a new role.
 * @summary Create Role
 * {@link /v1/workspaces/:workspaceId/roles}
 */
export async function createRole(
	{
		workspaceId,
	}: {
		workspaceId: CreateRolePathParams['workspaceId']
	},
	data: CreateRoleMutationRequest,
	params?: CreateRoleQueryParams,
	headers?: CreateRoleHeaderParams,
	config: Partial<RequestConfig<CreateRoleMutationRequest>> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const requestData = data

	const res = await request<
		CreateRoleMutationResponse,
		ResponseErrorConfig<CreateRole400 | CreateRole500>,
		CreateRoleMutationRequest
	>({
		method: 'POST',
		url: getCreateRoleUrl({
			workspaceId,
		}).url.toString(),
		params,
		data: requestData,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
