/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { CreateSubscriptionMutationRequest, CreateSubscriptionMutationResponse, CreateSubscriptionPathParams, CreateSubscriptionQueryParams, CreateSubscriptionHeaderParams, CreateSubscription400, CreateSubscription500 } from "../types/CreateSubscription";

function getCreateSubscriptionUrl({ workspaceId }: { workspaceId: CreateSubscriptionPathParams["workspaceId"] }) {
  const res = { method: 'POST', url: `http://localhost:4000/v1/workspaces/${workspaceId}/subscriptions` as const }  
  return res
}

/**
 * @description Creates a new subscription.
 * @summary Create Subscription
 * {@link /v1/workspaces/:workspaceId/subscriptions}
 */
export async function createSubscription({ workspaceId }: { workspaceId: CreateSubscriptionPathParams["workspaceId"] }, data?: CreateSubscriptionMutationRequest, params?: CreateSubscriptionQueryParams, headers?: CreateSubscriptionHeaderParams, config: Partial<RequestConfig<CreateSubscriptionMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateSubscriptionMutationResponse, ResponseErrorConfig<CreateSubscription400 | CreateSubscription500>, CreateSubscriptionMutationRequest>({ method : "POST", url : getCreateSubscriptionUrl({ workspaceId }).url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}