/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { CreateOrganizationMutationRequest, CreateOrganizationMutationResponse, CreateOrganizationPathParams, CreateOrganizationQueryParams, CreateOrganizationHeaderParams, CreateOrganization400, CreateOrganization500 } from "../types/CreateOrganization";

function getCreateOrganizationUrl({ workspaceId }: { workspaceId: CreateOrganizationPathParams["workspaceId"] }) {
  const res = { method: 'POST', url: `http://localhost:4000/v1/workspaces/${workspaceId}/organizations` as const }  
  return res
}

/**
 * @description Creates a new organization.
 * @summary Create Organization
 * {@link /v1/workspaces/:workspaceId/organizations}
 */
export async function createOrganization({ workspaceId }: { workspaceId: CreateOrganizationPathParams["workspaceId"] }, data: CreateOrganizationMutationRequest, params?: CreateOrganizationQueryParams, headers?: CreateOrganizationHeaderParams, config: Partial<RequestConfig<CreateOrganizationMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateOrganizationMutationResponse, ResponseErrorConfig<CreateOrganization400 | CreateOrganization500>, CreateOrganizationMutationRequest>({ method : "POST", url : getCreateOrganizationUrl({ workspaceId }).url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}