/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	CreateWorkspaceMutationRequest,
	CreateWorkspaceMutationResponse,
	CreateWorkspaceQueryParams,
	CreateWorkspaceHeaderParams,
	CreateWorkspace400,
	CreateWorkspace500,
} from '../types/CreateWorkspace'

function getCreateWorkspaceUrl() {
	const res = {
		method: 'POST',
		url: `http://localhost:4000/v1/workspaces` as const,
	}
	return res
}

/**
 * @description Creates a new workspace.
 * @summary Create Workspace
 * {@link /v1/workspaces}
 */
export async function createWorkspace(
	data: CreateWorkspaceMutationRequest,
	params?: CreateWorkspaceQueryParams,
	headers?: CreateWorkspaceHeaderParams,
	config: Partial<RequestConfig<CreateWorkspaceMutationRequest>> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const requestData = data

	const res = await request<
		CreateWorkspaceMutationResponse,
		ResponseErrorConfig<CreateWorkspace400 | CreateWorkspace500>,
		CreateWorkspaceMutationRequest
	>({
		method: 'POST',
		url: getCreateWorkspaceUrl().url.toString(),
		params,
		data: requestData,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
