/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { DeactivateProfileMutationResponse, DeactivateProfileQueryParams, DeactivateProfileHeaderParams, DeactivateProfile400, DeactivateProfile401, DeactivateProfile500 } from "../types/DeactivateProfile";

function getDeactivateProfileUrl() {
  const res = { method: 'DELETE', url: `http://localhost:4000//v1/profile` as const }  
  return res
}

/**
 * @description Deactivates the authenticated account.
 * @summary Deactivate Profile
 * {@link /v1/profile}
 */
export async function deactivateProfile(params?: DeactivateProfileQueryParams, headers?: DeactivateProfileHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeactivateProfileMutationResponse, ResponseErrorConfig<DeactivateProfile400 | DeactivateProfile401 | DeactivateProfile500>, unknown>({ method : "DELETE", url : getDeactivateProfileUrl().url.toString(), params, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}