/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { DeleteRoleMutationResponse, DeleteRolePathParams, DeleteRoleQueryParams, DeleteRoleHeaderParams, DeleteRole400, DeleteRole500 } from "../types/DeleteRole";

function getDeleteRoleUrl({ workspaceId, roleId }: { workspaceId: DeleteRolePathParams["workspaceId"]; roleId: DeleteRolePathParams["roleId"] }) {
  const res = { method: 'DELETE', url: `http://localhost:4000/v1/workspaces/${workspaceId}/roles/${roleId}` as const }  
  return res
}

/**
 * @description Deletes a role by their ID.
 * @summary Delete Role
 * {@link /v1/workspaces/:workspaceId/roles/:roleId}
 */
export async function deleteRole({ workspaceId, roleId }: { workspaceId: DeleteRolePathParams["workspaceId"]; roleId: DeleteRolePathParams["roleId"] }, params?: DeleteRoleQueryParams, headers?: DeleteRoleHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteRoleMutationResponse, ResponseErrorConfig<DeleteRole400 | DeleteRole500>, unknown>({ method : "DELETE", url : getDeleteRoleUrl({ workspaceId, roleId }).url.toString(), params, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}