/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	DeleteUserMutationResponse,
	DeleteUserPathParams,
	DeleteUserQueryParams,
	DeleteUserHeaderParams,
	DeleteUser400,
	DeleteUser500,
} from '../types/DeleteUser'

function getDeleteUserUrl({
	userId,
	workspaceId,
}: {
	userId: DeleteUserPathParams['userId']
	workspaceId: DeleteUserPathParams['workspaceId']
}) {
	const res = {
		method: 'DELETE',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/users/${userId}` as const,
	}
	return res
}

/**
 * @description Deletes a user by their ID.
 * @summary Delete User
 * {@link /v1/workspaces/:workspaceId/users/:userId}
 */
export async function deleteUser(
	{
		userId,
		workspaceId,
	}: {
		userId: DeleteUserPathParams['userId']
		workspaceId: DeleteUserPathParams['workspaceId']
	},
	params?: DeleteUserQueryParams,
	headers?: DeleteUserHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		DeleteUserMutationResponse,
		ResponseErrorConfig<DeleteUser400 | DeleteUser500>,
		unknown
	>({
		method: 'DELETE',
		url: getDeleteUserUrl({
			userId,
			workspaceId,
		}).url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
