/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { ForgotPasswordMutationRequest, ForgotPasswordMutationResponse, ForgotPasswordQueryParams, ForgotPasswordHeaderParams, ForgotPassword400, ForgotPassword401, ForgotPassword403, ForgotPassword404, ForgotPassword409, ForgotPassword500 } from "../types/ForgotPassword";

function getForgotPasswordUrl() {
  const res = { method: 'POST', url: `http://localhost:4000//v1/auth/forgot-password` as const }  
  return res
}

/**
 * @description Validates the OTP sent to the user’s email and allows them to reset their password.
 * @summary Forgot Password
 * {@link /v1/auth/forgot-password}
 */
export async function forgotPassword(data?: ForgotPasswordMutationRequest, params?: ForgotPasswordQueryParams, headers?: ForgotPasswordHeaderParams, config: Partial<RequestConfig<ForgotPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ForgotPasswordMutationResponse, ResponseErrorConfig<ForgotPassword400 | ForgotPassword401 | ForgotPassword403 | ForgotPassword404 | ForgotPassword409 | ForgotPassword500>, ForgotPasswordMutationRequest>({ method : "POST", url : getForgotPasswordUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}