/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	GetInviteQueryResponse,
	GetInvitePathParams,
	GetInviteQueryParams,
	GetInviteHeaderParams,
	GetInvite400,
	GetInvite401,
	GetInvite404,
	GetInvite500,
} from '../types/GetInvite'

function getGetInviteUrl({
	workspaceId,
	inviteId,
}: {
	workspaceId: GetInvitePathParams['workspaceId']
	inviteId: GetInvitePathParams['inviteId']
}) {
	const res = {
		method: 'GET',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/invites/${inviteId}` as const,
	}
	return res
}

/**
 * @description Retrieves details of a specific invite.
 * @summary Get Invite
 * {@link /v1/workspaces/:workspaceId/invites/:inviteId}
 */
export async function getInvite(
	{
		workspaceId,
		inviteId,
	}: {
		workspaceId: GetInvitePathParams['workspaceId']
		inviteId: GetInvitePathParams['inviteId']
	},
	params?: GetInviteQueryParams,
	headers?: GetInviteHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		GetInviteQueryResponse,
		ResponseErrorConfig<
			GetInvite400 | GetInvite401 | GetInvite404 | GetInvite500
		>,
		unknown
	>({
		method: 'GET',
		url: getGetInviteUrl({
			workspaceId,
			inviteId,
		}).url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
