/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	GetInvoiceQueryResponse,
	GetInvoicePathParams,
	GetInvoiceQueryParams,
	GetInvoiceHeaderParams,
	GetInvoice400,
	GetInvoice500,
} from '../types/GetInvoice'

function getGetInvoiceUrl({
	workspaceId,
	invoiceId,
}: {
	workspaceId: GetInvoicePathParams['workspaceId']
	invoiceId: GetInvoicePathParams['invoiceId']
}) {
	const res = {
		method: 'GET',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/invoices/${invoiceId}` as const,
	}
	return res
}

/**
 * @description Retrieves a single invoice by their ID.
 * @summary Get Invoice
 * {@link /v1/workspaces/:workspaceId/invoices/:invoiceId}
 */
export async function getInvoice(
	{
		workspaceId,
		invoiceId,
	}: {
		workspaceId: GetInvoicePathParams['workspaceId']
		invoiceId: GetInvoicePathParams['invoiceId']
	},
	params?: GetInvoiceQueryParams,
	headers?: GetInvoiceHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		GetInvoiceQueryResponse,
		ResponseErrorConfig<GetInvoice400 | GetInvoice500>,
		unknown
	>({
		method: 'GET',
		url: getGetInvoiceUrl({
			workspaceId,
			invoiceId,
		}).url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
