/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { GetOrganizationQueryResponse, GetOrganizationPathParams, GetOrganizationQueryParams, GetOrganizationHeaderParams, GetOrganization400, GetOrganization500 } from "../types/GetOrganization";

function getGetOrganizationUrl({ workspaceId, organizationId }: { workspaceId: GetOrganizationPathParams["workspaceId"]; organizationId: GetOrganizationPathParams["organizationId"] }) {
  const res = { method: 'GET', url: `http://localhost:4000/v1/workspaces/${workspaceId}/organizations/${organizationId}` as const }  
  return res
}

/**
 * @description Retrieves a single organization by their ID.
 * @summary Get Organization
 * {@link /v1/workspaces/:workspaceId/organizations/:organizationId}
 */
export async function getOrganization({ workspaceId, organizationId }: { workspaceId: GetOrganizationPathParams["workspaceId"]; organizationId: GetOrganizationPathParams["organizationId"] }, params?: GetOrganizationQueryParams, headers?: GetOrganizationHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetOrganizationQueryResponse, ResponseErrorConfig<GetOrganization400 | GetOrganization500>, unknown>({ method : "GET", url : getGetOrganizationUrl({ workspaceId, organizationId }).url.toString(), params, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}