/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { GetPlanQueryResponse, GetPlanPathParams, GetPlanQueryParams, GetPlanHeaderParams, GetPlan400, GetPlan404, GetPlan500 } from "../types/GetPlan";

function getGetPlanUrl({ planId }: { planId: GetPlanPathParams["planId"] }) {
  const res = { method: 'GET', url: `http://localhost:4000//v1/plans/${planId}` as const }  
  return res
}

/**
 * @description Retrieves a single plan by their ID.
 * @summary Get Plan
 * {@link /v1/plans/:planId}
 */
export async function getPlan({ planId }: { planId: GetPlanPathParams["planId"] }, params?: GetPlanQueryParams, headers?: GetPlanHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPlanQueryResponse, ResponseErrorConfig<GetPlan400 | GetPlan404 | GetPlan500>, unknown>({ method : "GET", url : getGetPlanUrl({ planId }).url.toString(), params, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}