/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../../kubb.client'
import type {
	RequestConfig,
	ResponseErrorConfig,
} from '../../../../kubb.client'
import type {
	GetPermissionsQueryResponse,
	GetPermissionsQueryParams,
	GetPermissionsHeaderParams,
	GetPermissions400,
	GetPermissions500,
} from '../types/GetPermissions'

function getGetPermissionsUrl() {
	const res = {
		method: 'GET',
		url: `http://localhost:6000//v1/permissions` as const,
	}
	return res
}

/**
 * @description Retrieves a list of all available permission used for access control within the API.
 * @summary List Permissions
 * {@link /v1/permissions}
 */
export async function getPermissions(
	params?: GetPermissionsQueryParams,
	headers?: GetPermissionsHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		GetPermissionsQueryResponse,
		ResponseErrorConfig<GetPermissions400 | GetPermissions500>,
		unknown
	>({
		method: 'GET',
		url: getGetPermissionsUrl().url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
