/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { GetSubscriptionQueryResponse, GetSubscriptionPathParams, GetSubscriptionQueryParams, GetSubscriptionHeaderParams, GetSubscription400, GetSubscription500 } from "../types/GetSubscription";

function getGetSubscriptionUrl({ workspaceId, subscriptionId }: { workspaceId: GetSubscriptionPathParams["workspaceId"]; subscriptionId: GetSubscriptionPathParams["subscriptionId"] }) {
  const res = { method: 'GET', url: `http://localhost:4000/v1/workspaces/${workspaceId}/subscriptions/${subscriptionId}` as const }  
  return res
}

/**
 * @description Retrieves a current subscription.
 * @summary Get Subscription
 * {@link /v1/workspaces/:workspaceId/subscriptions/:subscriptionId}
 */
export async function getSubscription({ workspaceId, subscriptionId }: { workspaceId: GetSubscriptionPathParams["workspaceId"]; subscriptionId: GetSubscriptionPathParams["subscriptionId"] }, params?: GetSubscriptionQueryParams, headers?: GetSubscriptionHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetSubscriptionQueryResponse, ResponseErrorConfig<GetSubscription400 | GetSubscription500>, unknown>({ method : "GET", url : getGetSubscriptionUrl({ workspaceId, subscriptionId }).url.toString(), params, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}