/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	GetUserQueryResponse,
	GetUserPathParams,
	GetUserQueryParams,
	GetUserHeaderParams,
	GetUser400,
	GetUser500,
} from '../types/GetUser'

function getGetUserUrl({
	userId,
	workspaceId,
}: {
	userId: GetUserPathParams['userId']
	workspaceId: GetUserPathParams['workspaceId']
}) {
	const res = {
		method: 'GET',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/users/${userId}` as const,
	}
	return res
}

/**
 * @description Retrieves a single user by their ID.
 * @summary Get User
 * {@link /v1/workspaces/:workspaceId/users/:userId}
 */
export async function getUser(
	{
		userId,
		workspaceId,
	}: {
		userId: GetUserPathParams['userId']
		workspaceId: GetUserPathParams['workspaceId']
	},
	params?: GetUserQueryParams,
	headers?: GetUserHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		GetUserQueryResponse,
		ResponseErrorConfig<GetUser400 | GetUser500>,
		unknown
	>({
		method: 'GET',
		url: getGetUserUrl({
			userId,
			workspaceId,
		}).url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
