/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	GetUpcomingInvoiceQueryResponse,
	GetUpcomingInvoicePathParams,
	GetUpcomingInvoiceQueryParams,
	GetUpcomingInvoiceHeaderParams,
	GetUpcomingInvoice400,
	GetUpcomingInvoice500,
} from '../types/GetUpcomingInvoice'

function getGetUpcomingInvoiceUrl({
	workspaceId,
}: {
	workspaceId: GetUpcomingInvoicePathParams['workspaceId']
}) {
	const res = {
		method: 'GET',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/invoices/upcoming` as const,
	}
	return res
}

/**
 * @description Retrieves the upcoming invoice for a workspace.
 * @summary Get Upcoming Invoice
 * {@link /v1/workspaces/:workspaceId/invoices/upcoming}
 */
export async function getUpcomingInvoice(
	{
		workspaceId,
	}: {
		workspaceId: GetUpcomingInvoicePathParams['workspaceId']
	},
	params?: GetUpcomingInvoiceQueryParams,
	headers?: GetUpcomingInvoiceHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		GetUpcomingInvoiceQueryResponse,
		ResponseErrorConfig<GetUpcomingInvoice400 | GetUpcomingInvoice500>,
		unknown
	>({
		method: 'GET',
		url: getGetUpcomingInvoiceUrl({
			workspaceId,
		}).url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
