/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	ListInvoicesQueryResponse,
	ListInvoicesPathParams,
	ListInvoicesQueryParams,
	ListInvoicesHeaderParams,
	ListInvoices400,
	ListInvoices500,
} from '../types/ListInvoices'

function getListInvoicesUrl({
	workspaceId,
}: {
	workspaceId: ListInvoicesPathParams['workspaceId']
}) {
	const res = {
		method: 'GET',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/invoices` as const,
	}
	return res
}

/**
 * @description Retrieves a list of invoices.
 * @summary List Invoices
 * {@link /v1/workspaces/:workspaceId/invoices}
 */
export async function listInvoices(
	{
		workspaceId,
	}: {
		workspaceId: ListInvoicesPathParams['workspaceId']
	},
	params: ListInvoicesQueryParams,
	headers?: ListInvoicesHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		ListInvoicesQueryResponse,
		ResponseErrorConfig<ListInvoices400 | ListInvoices500>,
		unknown
	>({
		method: 'GET',
		url: getListInvoicesUrl({
			workspaceId,
		}).url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
