/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	ListOrganizationsQueryResponse,
	ListOrganizationsPathParams,
	ListOrganizationsQueryParams,
	ListOrganizationsHeaderParams,
	ListOrganizations400,
	ListOrganizations500,
} from '../types/ListOrganizations'

function getListOrganizationsUrl({
	workspaceId,
}: {
	workspaceId: ListOrganizationsPathParams['workspaceId']
}) {
	const res = {
		method: 'GET',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/organizations` as const,
	}
	return res
}

/**
 * @description Retrieves a list of organizations.
 * @summary List Organizations
 * {@link /v1/workspaces/:workspaceId/organizations}
 */
export async function listOrganizations(
	{
		workspaceId,
	}: {
		workspaceId: ListOrganizationsPathParams['workspaceId']
	},
	params?: ListOrganizationsQueryParams,
	headers?: ListOrganizationsHeaderParams,
	config: Partial<RequestConfig> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		ListOrganizationsQueryResponse,
		ResponseErrorConfig<ListOrganizations400 | ListOrganizations500>,
		unknown
	>({
		method: 'GET',
		url: getListOrganizationsUrl({
			workspaceId,
		}).url.toString(),
		params,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
