/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { ListPermissionsQueryResponse, ListPermissionsQueryParams, ListPermissionsHeaderParams, ListPermissions400, ListPermissions500 } from "../types/ListPermissions";

function getListPermissionsUrl() {
  const res = { method: 'GET', url: `http://localhost:4000/v1/permissions` as const }  
  return res
}

/**
 * @description Retrieves a list of all available permission used for access control within the API.
 * @summary List Permissions
 * {@link /v1/permissions}
 */
export async function listPermissions(params?: ListPermissionsQueryParams, headers?: ListPermissionsHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListPermissionsQueryResponse, ResponseErrorConfig<ListPermissions400 | ListPermissions500>, unknown>({ method : "GET", url : getListPermissionsUrl().url.toString(), params, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}