/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { PasswordLessMutationRequest, PasswordLessMutationResponse, PasswordLessQueryParams, PasswordLessHeaderParams, PasswordLess400, PasswordLess401, PasswordLess403, PasswordLess404, PasswordLess409, PasswordLess500 } from "../types/PasswordLess";

function getPasswordLessUrl() {
  const res = { method: 'POST', url: `http://localhost:4000//v1/auth/password-less` as const }  
  return res
}

/**
 * @description Allows users to authenticate by using an OTP sent to their email, without requiring a password.
 * @summary Password Less
 * {@link /v1/auth/password-less}
 */
export async function passwordLess(data?: PasswordLessMutationRequest, params?: PasswordLessQueryParams, headers?: PasswordLessHeaderParams, config: Partial<RequestConfig<PasswordLessMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PasswordLessMutationResponse, ResponseErrorConfig<PasswordLess400 | PasswordLess401 | PasswordLess403 | PasswordLess404 | PasswordLess409 | PasswordLess500>, PasswordLessMutationRequest>({ method : "POST", url : getPasswordLessUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}