/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { SendPasswordLessOTPMutationRequest, SendPasswordLessOTPMutationResponse, SendPasswordLessOTPQueryParams, SendPasswordLessOTPHeaderParams, SendPasswordLessOTP400, SendPasswordLessOTP404, SendPasswordLessOTP409, SendPasswordLessOTP500 } from "../types/SendPasswordLessOTP";

function getSendPasswordLessOTPUrl() {
  const res = { method: 'POST', url: `http://localhost:4000//v1/otps/password-less` as const }  
  return res
}

/**
 * @description Generates and sends a one-time password (OTP) to the user’s email address for password-less authentication, allowing secure sign-in without a password.
 * @summary Send Password Less OTP
 * {@link /v1/otps/password-less}
 */
export async function sendPasswordLessOTP(data: SendPasswordLessOTPMutationRequest, params?: SendPasswordLessOTPQueryParams, headers?: SendPasswordLessOTPHeaderParams, config: Partial<RequestConfig<SendPasswordLessOTPMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SendPasswordLessOTPMutationResponse, ResponseErrorConfig<SendPasswordLessOTP400 | SendPasswordLessOTP404 | SendPasswordLessOTP409 | SendPasswordLessOTP500>, SendPasswordLessOTPMutationRequest>({ method : "POST", url : getSendPasswordLessOTPUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}