/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { SendForgotPasswordOTPMutationRequest, SendForgotPasswordOTPMutationResponse, SendForgotPasswordOTPQueryParams, SendForgotPasswordOTPHeaderParams, SendForgotPasswordOTP400, SendForgotPasswordOTP404, SendForgotPasswordOTP409, SendForgotPasswordOTP500 } from "../types/SendForgotPasswordOTP";

function getSendForgotPasswordOTPUrl() {
  const res = { method: 'POST', url: `http://localhost:4000//v1/otps/forgot-password` as const }  
  return res
}

/**
 * @description Generates and sends a one-time password (OTP) to the user’s email address for the purpose of validating a password reset request.
 * @summary Send Forgot Password OTP
 * {@link /v1/otps/forgot-password}
 */
export async function sendForgotPasswordOTP(data: SendForgotPasswordOTPMutationRequest, params?: SendForgotPasswordOTPQueryParams, headers?: SendForgotPasswordOTPHeaderParams, config: Partial<RequestConfig<SendForgotPasswordOTPMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SendForgotPasswordOTPMutationResponse, ResponseErrorConfig<SendForgotPasswordOTP400 | SendForgotPasswordOTP404 | SendForgotPasswordOTP409 | SendForgotPasswordOTP500>, SendForgotPasswordOTPMutationRequest>({ method : "POST", url : getSendForgotPasswordOTPUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}