/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { SendUpdateEmailOTPMutationRequest, SendUpdateEmailOTPMutationResponse, SendUpdateEmailOTPQueryParams, SendUpdateEmailOTPHeaderParams, SendUpdateEmailOTP400, SendUpdateEmailOTP409, SendUpdateEmailOTP500 } from "../types/SendUpdateEmailOTP";

function getSendUpdateEmailOTPUrl() {
  const res = { method: 'POST', url: `http://localhost:4000/v1/otps/update-email` as const }  
  return res
}

/**
 * @description Generates and sends a one-time password (OTP) to the user’s email address for the purpose of validating an email address reset request.
 * @summary Send Email Update OTP
 * {@link /v1/otps/update-email}
 */
export async function sendUpdateEmailOTP(data: SendUpdateEmailOTPMutationRequest, params?: SendUpdateEmailOTPQueryParams, headers?: SendUpdateEmailOTPHeaderParams, config: Partial<RequestConfig<SendUpdateEmailOTPMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SendUpdateEmailOTPMutationResponse, ResponseErrorConfig<SendUpdateEmailOTP400 | SendUpdateEmailOTP409 | SendUpdateEmailOTP500>, SendUpdateEmailOTPMutationRequest>({ method : "POST", url : getSendUpdateEmailOTPUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}