/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { SignInMutationRequest, SignInMutationResponse, SignInQueryParams, SignInHeaderParams, SignIn400, SignIn401, SignIn500 } from "../types/SignIn";

function getSignInUrl() {
  const res = { method: 'POST', url: `http://localhost:4000/v1/auth/sign-in` as const }  
  return res
}

/**
 * @description Authenticates a user by verifying their email and password.
 * @summary Sign In
 * {@link /v1/auth/sign-in}
 */
export async function signIn(data: SignInMutationRequest, params?: SignInQueryParams, headers?: SignInHeaderParams, config: Partial<RequestConfig<SignInMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SignInMutationResponse, ResponseErrorConfig<SignIn400 | SignIn401 | SignIn500>, SignInMutationRequest>({ method : "POST", url : getSignInUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}