/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { SignUpMutationRequest, SignUpMutationResponse, SignUpQueryParams, SignUpHeaderParams, SignUp400, SignUp409, SignUp500 } from "../types/SignUp";

function getSignUpUrl() {
  const res = { method: 'POST', url: `http://localhost:4000//v1/auth/sign-up` as const }  
  return res
}

/**
 * @description Creates a new user account.
 * @summary Sign Up
 * {@link /v1/auth/sign-up}
 */
export async function signUp(data: SignUpMutationRequest, params?: SignUpQueryParams, headers?: SignUpHeaderParams, config: Partial<RequestConfig<SignUpMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SignUpMutationResponse, ResponseErrorConfig<SignUp400 | SignUp409 | SignUp500>, SignUpMutationRequest>({ method : "POST", url : getSignUpUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}