/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	SocialSignOnMutationRequest,
	SocialSignOnMutationResponse,
	SocialSignOnQueryParams,
	SocialSignOnHeaderParams,
	SocialSignOn400,
	SocialSignOn401,
	SocialSignOn500,
} from '../types/SocialSignOn'

function getSocialSignOnUrl() {
	const res = {
		method: 'POST',
		url: `http://localhost:4000/v1/auth/social-sign-on` as const,
	}
	return res
}

/**
 * @description Allows users to sign in using third-party services (such as Google, Facebook, etc.), providing a seamless authentication experience.
 * @summary Social Sign-On
 * {@link /v1/auth/social-sign-on}
 */
export async function socialSignOn(
	data: SocialSignOnMutationRequest,
	params?: SocialSignOnQueryParams,
	headers?: SocialSignOnHeaderParams,
	config: Partial<RequestConfig<SocialSignOnMutationRequest>> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const requestData = data

	const res = await request<
		SocialSignOnMutationResponse,
		ResponseErrorConfig<SocialSignOn400 | SocialSignOn401 | SocialSignOn500>,
		SocialSignOnMutationRequest
	>({
		method: 'POST',
		url: getSocialSignOnUrl().url.toString(),
		params,
		data: requestData,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
