/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { UpdateProfilePasswordMutationRequest, UpdateProfilePasswordMutationResponse, UpdateProfilePasswordQueryParams, UpdateProfilePasswordHeaderParams, UpdateProfilePassword400, UpdateProfilePassword401, UpdateProfilePassword500 } from "../types/UpdateProfilePassword";

function getUpdateProfilePasswordUrl() {
  const res = { method: 'PATCH', url: `http://localhost:4000/v1/profile/password` as const }  
  return res
}

/**
 * @description Updates the authenticated user password.
 * @summary Update Profile Password
 * {@link /v1/profile/password}
 */
export async function updateProfilePassword(data?: UpdateProfilePasswordMutationRequest, params?: UpdateProfilePasswordQueryParams, headers?: UpdateProfilePasswordHeaderParams, config: Partial<RequestConfig<UpdateProfilePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateProfilePasswordMutationResponse, ResponseErrorConfig<UpdateProfilePassword400 | UpdateProfilePassword401 | UpdateProfilePassword500>, UpdateProfilePasswordMutationRequest>({ method : "PATCH", url : getUpdateProfilePasswordUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}