/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { UpdateProfileEmailMutationRequest, UpdateProfileEmailMutationResponse, UpdateProfileEmailQueryParams, UpdateProfileEmailHeaderParams, UpdateProfileEmail400, UpdateProfileEmail401, UpdateProfileEmail403, UpdateProfileEmail404, UpdateProfileEmail409, UpdateProfileEmail500 } from "../types/UpdateProfileEmail";

function getUpdateProfileEmailUrl() {
  const res = { method: 'PATCH', url: `http://localhost:4000//v1/profile/email` as const }  
  return res
}

/**
 * @description Validates the OTP sent to the user's email and allows the user to reset their email.
 * @summary Update Profile Email
 * {@link /v1/profile/email}
 */
export async function updateProfileEmail(data?: UpdateProfileEmailMutationRequest, params?: UpdateProfileEmailQueryParams, headers?: UpdateProfileEmailHeaderParams, config: Partial<RequestConfig<UpdateProfileEmailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateProfileEmailMutationResponse, ResponseErrorConfig<UpdateProfileEmail400 | UpdateProfileEmail401 | UpdateProfileEmail403 | UpdateProfileEmail404 | UpdateProfileEmail409 | UpdateProfileEmail500>, UpdateProfileEmailMutationRequest>({ method : "PATCH", url : getUpdateProfileEmailUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}