/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { UpdateOrganizationMutationRequest, UpdateOrganizationMutationResponse, UpdateOrganizationPathParams, UpdateOrganizationQueryParams, UpdateOrganizationHeaderParams, UpdateOrganization400, UpdateOrganization500 } from "../types/UpdateOrganization";

function getUpdateOrganizationUrl({ workspaceId, organizationId }: { workspaceId: UpdateOrganizationPathParams["workspaceId"]; organizationId: UpdateOrganizationPathParams["organizationId"] }) {
  const res = { method: 'PATCH', url: `http://localhost:4000/v1/workspaces/${workspaceId}/organizations/${organizationId}` as const }  
  return res
}

/**
 * @description Updates an existing organization by their ID.
 * @summary Update Organization
 * {@link /v1/workspaces/:workspaceId/organizations/:organizationId}
 */
export async function updateOrganization({ workspaceId, organizationId }: { workspaceId: UpdateOrganizationPathParams["workspaceId"]; organizationId: UpdateOrganizationPathParams["organizationId"] }, data?: UpdateOrganizationMutationRequest, params?: UpdateOrganizationQueryParams, headers?: UpdateOrganizationHeaderParams, config: Partial<RequestConfig<UpdateOrganizationMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateOrganizationMutationResponse, ResponseErrorConfig<UpdateOrganization400 | UpdateOrganization500>, UpdateOrganizationMutationRequest>({ method : "PATCH", url : getUpdateOrganizationUrl({ workspaceId, organizationId }).url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}