/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { UpdateProfileMutationRequest, UpdateProfileMutationResponse, UpdateProfileQueryParams, UpdateProfileHeaderParams, UpdateProfile400, UpdateProfile401, UpdateProfile500 } from "../types/UpdateProfile";

function getUpdateProfileUrl() {
  const res = { method: 'PATCH', url: `http://localhost:4000//v1/profile` as const }  
  return res
}

/**
 * @description Updates and returns the authenticated profile.
 * @summary Update Profile
 * {@link /v1/profile}
 */
export async function updateProfile(data?: UpdateProfileMutationRequest, params?: UpdateProfileQueryParams, headers?: UpdateProfileHeaderParams, config: Partial<RequestConfig<UpdateProfileMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateProfileMutationResponse, ResponseErrorConfig<UpdateProfile400 | UpdateProfile401 | UpdateProfile500>, UpdateProfileMutationRequest>({ method : "PATCH", url : getUpdateProfileUrl().url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}