/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../../kubb.client'
import type { RequestConfig, ResponseErrorConfig } from '../../../kubb.client'
import type {
	UpdateUserMutationRequest,
	UpdateUserMutationResponse,
	UpdateUserPathParams,
	UpdateUserQueryParams,
	UpdateUserHeaderParams,
	UpdateUser400,
	UpdateUser500,
} from '../types/UpdateUser'

function getUpdateUserUrl({
	userId,
	workspaceId,
}: {
	userId: UpdateUserPathParams['userId']
	workspaceId: UpdateUserPathParams['workspaceId']
}) {
	const res = {
		method: 'PATCH',
		url: `http://localhost:4000/v1/workspaces/${workspaceId}/users/${userId}` as const,
	}
	return res
}

/**
 * @description Updates an existing user by their ID.
 * @summary Update User
 * {@link /v1/workspaces/:workspaceId/users/:userId}
 */
export async function updateUser(
	{
		userId,
		workspaceId,
	}: {
		userId: UpdateUserPathParams['userId']
		workspaceId: UpdateUserPathParams['workspaceId']
	},
	data?: UpdateUserMutationRequest,
	params?: UpdateUserQueryParams,
	headers?: UpdateUserHeaderParams,
	config: Partial<RequestConfig<UpdateUserMutationRequest>> & {
		client?: typeof fetch
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const requestData = data

	const res = await request<
		UpdateUserMutationResponse,
		ResponseErrorConfig<UpdateUser400 | UpdateUser500>,
		UpdateUserMutationRequest
	>({
		method: 'PATCH',
		url: getUpdateUserUrl({
			userId,
			workspaceId,
		}).url.toString(),
		params,
		data: requestData,
		...requestConfig,
		headers: {
			...headers,
			...requestConfig.headers,
		},
	})
	return res
}
