/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../../kubb.client";
import type { RequestConfig, ResponseErrorConfig } from "../../../kubb.client";
import type { ValidateOTPMutationRequest, ValidateOTPMutationResponse, ValidateOTPPathParams, ValidateOTPQueryParams, ValidateOTPHeaderParams, ValidateOTP400, ValidateOTP403, ValidateOTP404, ValidateOTP409, ValidateOTP500 } from "../types/ValidateOTP";

function getValidateOTPUrl({ otpId }: { otpId: ValidateOTPPathParams["otpId"] }) {
  const res = { method: 'POST', url: `http://localhost:4000//v1/otps/${otpId}/validate` as const }  
  return res
}

/**
 * @description Verifies a provided OTP against the expected value for user authentication.
 * @summary Validate OTP
 * {@link /v1/otps/:otpId/validate}
 */
export async function validateOTP({ otpId }: { otpId: ValidateOTPPathParams["otpId"] }, data: ValidateOTPMutationRequest, params?: ValidateOTPQueryParams, headers?: ValidateOTPHeaderParams, config: Partial<RequestConfig<ValidateOTPMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ValidateOTPMutationResponse, ResponseErrorConfig<ValidateOTP400 | ValidateOTP403 | ValidateOTP404 | ValidateOTP409 | ValidateOTP500>, ValidateOTPMutationRequest>({ method : "POST", url : getValidateOTPUrl({ otpId }).url.toString(), params, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res
}